:title-separator: {sp}|
= Инструкция по эксплуатации ПО "QS: Спецодежда"
Quality Solution 2026
версия 2.10
:organization: Quality Solution
:doctype: book
:sectnums:
:!chapter-signifier:
:toc: left
:icons: font
:toc-title: Содержание
:toclevels: 3
:imagesdir: images

== Общие сведения

Данный документ является руководством по эксплуатации программного обеспечения "QS: Спецодежда" (далее - ПО).

Все исключительные права на ПО принадлежат ООО "Качественные решения".

ПО имеет пользовательский графический интерфейс и устанавливается на рабочие места пользователей как клиентское приложение.
Данные хранятся в базе данных MariaDB или MySQL, размещенной на сервере организации либо в облачной инфраструктуре Quality Solution.

ПО разработано для учета спецодежды, средств индивидуальной защиты и другого имущества, выдаваемого сотрудникам организаций.

== Глоссарий

[cols="1,3"]
|===
|Термин |Описание

|ПО
|Программное обеспечение "QS: Спецодежда".

|СИЗ
|Средства индивидуальной защиты.

|Клиентское приложение
|Графическое приложение, установленное на компьютере пользователя и подключающееся к базе данных ПО.

|Сервер базы данных
|Сервер MariaDB или MySQL, на котором хранится база данных ПО.

|Личная карточка учета выдачи СИЗ
|Учетная карточка сотрудника, содержащая сведения о положенных, выданных и возвращенных СИЗ.

|Норма выдачи
|Правило обеспечения сотрудника спецодеждой или СИЗ по должности, профессии, дежурной норме или индивидуальному назначению.

|Складской документ
|Документ ПО, фиксирующий поступление, выдачу, возврат, перемещение, списание или иную складскую операцию.

|Журнал
|Табличный список объектов или документов в интерфейсе ПО.
|===

== Описание, назначение и возможности ПО

ПО "QS: Спецодежда" предназначено для ведения учета спецодежды, СИЗ и другого имущества, выдаваемого сотрудникам организаций.
ПО позволяет организовать работу специалистов по охране труда, складских сотрудников и администраторов базы данных в единой информационной системе.

ПО позволяет осуществлять:

* ведение в электронном виде личных карточек учета выдачи СИЗ;
* ведение справочников норм выдачи, включая отраслевые нормы и внутренние нормы организации;
* учет сроков носки и расчет даты следующей выдачи с учетом отпусков, периодов выдачи и дополнительных условий;
* ведение одного или нескольких складов спецодежды с привязкой склада к подразделению;
* учет поступлений, выдач, возвратов, перемещений, списаний и комплектации складских позиций;
* поразмерное прогнозирование закупки и складских запасов;
* выдачу спецодежды по бесконтактным картам сотрудников;
* учет сдачи спецодежды в обслуживание с использованием штрихкодов;
* импорт и экспорт данных;
* формирование отчетов и печатных форм;
* управление пользователями и правами доступа;
* просмотр истории изменений.

== Процесс установки ПО

ПО состоит из клиентской части и серверной части.
Клиентская часть устанавливается на компьютер пользователя, серверная часть представляет собой базу данных MariaDB или MySQL, размещенную на сервере организации либо в облачном сервисе Quality Solution.

Для установки клиентского приложения пользователь загружает актуальный дистрибутив с сайта разработчика https://files.qsolution.ru/Workwear/winsetup.exe, запускает установщик и выполняет предложенные им действия.
При необходимости установщик автоматически предложит установить дополнительные компоненты, требуемые для работы приложения.

Для хранения данных пользователь может использовать уже установленную СУБД MariaDB или MySQL либо установить ее на сервер согласно документации поставщика СУБД.
После подготовки сервера базы данных пользователь создает подключение в клиентском приложении и выполняет создание или подключение базы данных.

== Процесс запуска ПО

Для запуска ПО пользователь открывает приложение "QS: Спецодежда" с рабочего стола, из меню операционной системы или из каталога установки.
После запуска отображается окно входа, в котором пользователь выбирает подключение к базе данных, вводит имя пользователя и пароль, затем нажимает кнопку входа.

После успешной авторизации открывается главное окно ПО.
Доступный пользователю набор функций определяется настройками базы данных, редакцией ПО и правами учетной записи.

== Уровень подготовки пользователей

Пользователям не нужно проходить специальную техническую подготовку для работы с ПО.
Пользователи ПО должны обладать следующими минимальными навыками:

* базовые навыки работы на персональном компьютере с современными операционными системами;
* умение работать с клавиатурой, мышью, окнами приложений и файлами;
* понимание используемых в организации процессов учета спецодежды, СИЗ, складских операций и кадровой структуры.

Администраторы ПО дополнительно должны обладать базовыми навыками администрирования рабочих мест, сетевых подключений, пользователей и серверов баз данных MariaDB или MySQL.

== Основные компоненты ПО

В данном разделе описаны основные компоненты пользовательского и административного интерфейса ПО.
Разделы, относящиеся к личному кабинету сотрудника, мобильному приложению, постаматам и предварительному посещению склада, в настоящий документ не включены.

:leveloffset: 2

include::pages/interface.adoc[]

include::pages/organization.adoc[]

include::pages/regulations.adoc[]

include::pages/employees.adoc[]

include::pages/stock.adoc[]

include::pages/stock-documents.adoc[]

include::pages/reports.adoc[]

include::pages/settings.adoc[]

include::pages/manipulation.adoc[]

include::pages/history-log.adoc[]

include::pages/import.adoc[]

include::pages/export.adoc[]

include::pages/clothing-service.adoc[]

:leveloffset: 0

== Процесс завершения работы ПО

Для завершения работы пользователь закрывает главное окно приложения "QS: Спецодежда".
Если в открытых окнах есть несохраненные изменения, ПО предложит сохранить или отменить их перед закрытием.

После закрытия клиентского приложения соединение с базой данных завершается.
Дополнительные действия со стороны пользователя не требуются.

== Контакты

Для контактов с командой разработчиков просьба обращаться по следующим контактам:

Тел.: +7 (812) 309-71-77

e-mail: support@qsolution.ru
