[[_license]]
= Условия использования и распространения
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

Программа распространяется на условиях лицензии GPL-2 (GNU GENERAL PUBLIC LICENSE), текст лицензии находится в папке с программой в файле COPYING.

Вкратце, эта лицензия позволяет вам, использовать программу в любых целях, свободно модифицировать(дорабатывать) ее для своих нужд и распространять ее, то есть передавать другим пользователям в неизменном виде.
Но если вы изменили что-то в программе и распространяете модифицированную версию, вы обязаны распространять ее на тех же условиях, то есть предоставить всем пользователям модифицированной версии исходный код своих доработок.

== Преимущества

Открытый подход к разработке нашего продукта несет несколько преимуществ Вам, как конечному пользователю программы.

* Мы не накладываем на вас, множества ограничений, которые как правило присутствуют в лицензионных соглашениях большинства http://ru.wikipedia.org/wiki/Проприетарное_программное_обеспечение[проприетарных продуктов], например на количество пользователей или на условия запуска, например отсутствие возможности работать в терминальном режиме или на цели использования, например для коммерческого использования своя цена и тому подобные ограничения.
* Мы позволяем Вам при необходимости самим дорабатывать продукт или нанять для этого любого программиста. Что как правило нельзя сделать с закрытыми проприетарными продуктами.
* У Вас нет прямой зависимости о действий разработчика, так называемый вендор лок, который часто применяется в софтверной индустрии. Для вытягивания дополнительный денег с пользователей.
* Если у вас молодой бизнес, вы можете использовать наш продукт как есть, без какой-либо платы. Что может дать вам дополнительные возможности для роста.

При этом мы надеемся на добросовестность наших пользователей и клиентов и если Вы желаете, чтобы продукт развивался и улучшался, поддержите нас приобретя платную поддержку или закажите разработку необходимых для вас функций.

Если Вы дорабатываете программу своими силами, не забывайте, что отправляя нам свои доработки Вы можете значительно сократить стоимость поддержки вашей ветки, за счет объединения усилий.

Мы также приглашаем к сотрудничеству партнеров для совместного развития и распространения программы.

== Использованные сторонние компоненты

В этом разделе перечислены все компоненты, библиотеки, изображения или другие произведения сторонних авторов, используемые нами в приложении.

=== Библиотеки

.Используемые библиотеки
[cols="1,1,1", options="header"]
|===
| Название
| Сайт
| Лицензия

|GTK# + Mono
|http://www.mono-project.com[mono project]
|LGPL2

|Majorsilence Reporting(FyiReporting)
|https://github.com/majorsilence/My-FyiReporting[github]
|Apache License v2.0

|Nini
|http://nini.sourceforge.net/[nini.sourceforge.net]
|MIT license
|===