= Установка на Linux
:experimental:

Программа «QS: Спецодежда» распространяется в виде пакетов для различных дистрибутивов Linux.
Ниже описан порядок установки через пакетный менеджер с подключением нашего репозитория.

После установки программы вам также потребуется сервер баз данных MariaDB или MySQL.
Инструкция по его установке находится в разделе <<install.adoc#InstallDBServer,Установка сервера базы данных>>.

[#alt-linux]
== AltLinux

Инструкция проверена на AltLinux p11 (11.x).

=== Подключение репозитория

Добавьте наш репозиторий в список источников пакетов:

[source,bash]
----
echo "rpm https://repo.qsolution.ru/alt/workwear x86_64 workwear" \
    | sudo tee /etc/apt/sources.list.d/qsolution-workwear.list
----

Обновите список пакетов:

[source,bash]
----
sudo apt-get update
----

=== Установка

[source,bash]
----
sudo apt-get install qs-workwear
----

После установки программа появится в меню приложений в разделе *Офис* под названием *QS: Спецодежда*.

Запустить программу также можно из терминала:

[source,bash]
----
workwear
----

=== Обновление

Обновление до новой версии выполняется стандартными средствами:

[source,bash]
----
sudo apt-get update
sudo apt-get upgrade qs-workwear
----

