[preface]
= Введение

Программа предназначена для ведения склада спецодежды, СИЗ и другого имущества, выдаваемого сотрудникам в организациях.

== Основные возможности

* Ведение в электронном виде личных карточек учета выдачи СИЗ
* Ведение справочников норм выдачи, как отраслевых норм выдачи спецодежды, так и внутренних норм организации
* Учет сроков носки и времени следующей выдачи, с учетом данных об отпуске сотрудника, периодах выдачи СИЗ и других условий.
* Ведение нескольких складов спецодежды, с возможностью привязки склада к подразделению
* Поразмерное прогнозирование закупки
* Выдача спецодежды по бесконтактным картам сотрудников
* Мобильное приложение с личным кабинетом сотрудника
* Просмотр истории изменений

== Рекомендуемая последовательность ввода данных

. Ввод справочных данных
.. В справочнике <<organization.adoc#organizations,«Организации»>> изменить название своей организации.
.. В справочнике <<organization.adoc#subdivisions,«Подразделения»>> создать подразделения, за которыми будут закреплены сотрудники. При желании детализации рабочего места, можно также создать <<organization.adoc#departments,отделы>>.
.. Заполняем <<regulations.adoc#norms,нормы выдачи>> на предприятии по профессиям, предварительно можно заполнить справочник <<regulations.adoc#protection-tools,«Номенклатура нормы»>>, если список выдаваемых СИЗ известен заранее, если нет, можно его заполнять в процессе ввода норм. Нормы выдачи можно вводить с привязкой к <<regulations.adoc#regulation-doc,нормативному документу>>, для этого предварительно нужно его создать.
.. Заполняем справочник <<organization.adoc#posts,должностей>>, при привязке нормы вручную сотрудникам этот шаг можно пропустить.
.. Вводим <<employees.adoc#employees,личные карточки учета выдачи СИЗ>> на сотрудников, которым необходимо будет получать спецодежду. Или <<import.adoc#employees-excel-import,загружаем сотрудников из Excel>>, в этом случае можно пропустить создание (подразделений, отделов и должностей) они могут быть созданы автоматически при создании сотрудников.
.. Привязываем сотрудников к нормам выдачи, либо вручную, либо по должности.
.. Если сотрудникам уже выдавалась спецодежда, вводим даты предыдущих выдач через функцию <<employees.adoc#issue-siz,установка даты выдачи>>.
.. Если планируется работать с несколькими складами, нужно их создать в справочнике <<stock.adoc#warehouses,«Склады»>>.
. Ввод данных учета
.. Если введены все данные по сотрудникам, можно рассчитать потребность в спецодежде через отчет <<reports.adoc#request-sheet,«Заявка на спецодежду»>>.
.. Внесите текущие остатки на складе через ввод <<stock-documents.adoc#stock-income,документа поступления>>, если остатков нет необходимо внести поступления. При вводе поступления можно заполнить справочник <<stock.adoc#nomenclatures,«Номенклатуры»>>.
.. <<employees.adoc#issue-siz,Выдача спецодежды>> сотрудникам.
.. По необходимости <<stock-documents.adoc#employee-return,возврат>> или <<stock-documents.adoc#writeoff,списание>> спецодежды.
