[preface]
= Введение

Программа предназначена для ведения склада спецодежды, СИЗ и другого имущества, выдаваемого сотрудникам в организациях.

== Основные возможности

* Ведение в электронном виде личных карточек учета выдачи СИЗ.
* Ведение справочников норм выдачи, как отраслевых норм выдачи спецодежды, так и внутренних норм организации.
* Учет сроков носки и времени следующей выдачи, с учетом данных об отпуске сотрудника, периодах выдачи СИЗ и других условий.
* Ведение нескольких складов спецодежды, с возможностью привязки склада к подразделению.
* Поразмерное прогнозирование закупки и складских запасов.
* Выдача спецодежды по бесконтактным картам сотрудников и через постаматы выдачи.
* Мобильное приложение с личным кабинетом сотрудника.
* Учет сдачи спецодежды в стирку с использованием штрихкодов.
* Просмотр истории изменений.

[#editions]
== Редакции программы

Существуют 4 редакции программы:

Однопользовательская:: Бесплатная редакция, рассчитанная на использование в небольших организация(до 50 сотрудников) в которых отсутствует специалист по охране труда.
Профессиональная:: Основная редакция продукта, подходящая для большинства организаций, позволяет специалистам по охране труда организовать учет и выдачу спецодежды.
Предприятие:: Расширенная редакция с дополнительными возможностями, предназначенная для больших организаций, предъявляющие повышенные требования к системе.
Спецаутсорсинг:: Редакция программы предоставляемая только в комплексе услуг по выдаче спецодежды и СИЗ от Спецаутсорсинг.

[#features]
.Возможности каждой редакции
[cols="2,^1,^1,^1,^1"]
|===
|Функциональность |Однопользовательская |Профессиональная |Предприятие |Спецаутсорсинг

5+^e|Ограничения

|Количество одновременных подключений к базе
|1
|по числу лицензий
|от 3-х
|не ограничено

|<<update.adoc##update-application,Обновление>> на следующий значительный релиз
|∞
|в течении года
|пока активен договор
|пока активен договор

|Уровень поддержки
|только ошибки
|в течении года, ServiceDesk, телефон и Email
|приоритетная + помощь в обработке данных
|учет, выдача и хранение под ключ

5+^e|Основные возможности

|<<employees.adoc#employees,Ведение карточек учета выдачи СИЗ>>
|✅
|✅
|✅
|✅

|<<regulations.adoc#norms,Ведение норм выдачи>>
|✅
|✅
|✅
|✅

|<<stock-documents.adoc#stock-documents,Ведение склада спецодежды>>
|✅
|✅
|✅
|✅

|<<regulations.adoc#duty-norms,Дежурные нормы>>
|❌
|✅
|✅
|✅

|<<stock.adoc#sizes,Редактирование размеров>>
|❌
|✅
|✅
|✅

|<<employees.adoc#vacations,Учет отпусков>>
|❌
|✅
|✅
|✅

|<<import.adoc#import,Импорт>> (Excel, 1С)
|❌
|✅
|✅
|✅

|<<regulations.adoc#norm-conditions,Условия нормы>>
|❌
|✅
|✅
|✅

|<<stock.adoc#warehouses,Работа с несколькими складами>>
|❌
|❌
|✅
|✅

|<<manipulation.adoc#manipulation,Групповая обработка объектов>>
|❌
|❌
|✅
|✅

|<<history-log.adoc#history-log,Просмотр истории изменений>>
|❌
|❌
|✅
|✅

|<<organization.adoc#employees-groups,Группы сотрудников>>
|❌
|❌
|✅
|✅

|<<stock.adoc#owners,Собственники имущества>>
|❌
|❌
|✅
|✅

|<<organization.adoc#mvz,Место возникновения затрат>>
|❌
|❌
|✅
|✅

|<<export.adoc#export,Экспорт прогноза выдач>> (для бюджета)
|❌
|❌
|✅
|✅

|<<stock.adoc#warehouse-forecast,Прогнозирование складских запасов>>
|❌
|❌
|✅
|✅

5+^e|Документы

|<<stock-documents.adoc#stock-income,Документ поступления>>
|✅
|✅
|✅
|✅

|<<stock-documents.adoc#employee-issue,Персональная выдача>>
|✅
|✅
|✅
|✅

|<<stock-documents.adoc#writeoff,Списание>>
|✅
|✅
|✅
|✅

|<<stock-documents.adoc#issuance-sheet,Ведомость МБ-7>>
|только из документов
|✅
|✅
|✅

|<<stock-documents.adoc#collective-issue,Документ коллективной выдачи>>
|❌
|✅
|✅
|✅

|<<stock-documents.adoc#complectation,Документ комплектации>>
|❌
|✅
|✅
|✅

|<<stock-documents.adoc#inspection,Документ переоценки>>
|❌
|✅
|✅
|❌

|<<stock-documents.adoc#transfer,Документ перемещения>>
|❌
|❌
|✅
|✅

5+^e|Отчеты

|<<reports.adoc#wear-statement,Сводная ведомость>>
|✅
|✅
|✅
|✅

|<<reports.adoc#list-by-size,Список по размерам>>
|✅
|✅
|✅
|✅

|<<reports.adoc#unissued,Справка по невыданному>>
|✅
|✅
|✅
|✅

|<<reports.adoc#average-annual-need,Среднегодовая потребность>>
|✅
|✅
|✅
|✅

|<<reports.adoc#stock-list,Складская ведомость>>
|❌
|✅
|✅
|✅

|<<reports.adoc#amount-issued,Справка по выданному>>
|❌
|✅
|✅
|✅

|<<reports.adoc#written-off,Справка по списаниям>>
|❌
|✅
|✅
|✅

|<<reports.adoc#request-sheet,Заявка на спецодежду>>
|❌
|✅
|✅
|✅

|<<reports.adoc#stock-operations,Справка по складским операциям>>
|❌
|❌
|✅
|✅

|<<reports.adoc#amount-employees-get-wear,Количество сотрудников получивших СИЗ>>
|❌
|❌
|✅
|✅

|<<reports.adoc#provision,Обеспеченность сотрудников>>
|❌
|❌
|✅
|✅

|<<reports.adoc#barcode-completeness,Покрытие маркировкой>>
|❌
|❌
|с модулем штрихкоды
|✅

5+^e|Мобильное приложение

|<<mobile-app.adoc#mobile-app,Мобильный кабинет сотрудника и Push уведомления о получении спецодежды>>
|❌
|✅ (покупается отдельно)
|✅ (покупается отдельно)
|✅

|<<mobile-app.adoc#claims,Обращения сотрудников>>
|❌
|❌
|✅
|✅

|<<mobile-app.adoc#ratings,Отзывы>>
|❌
|❌
|✅
|✅

|<<mobile-app.adoc,Спецкойны (программа лояльности)>>
|❌
|❌
|❌
|✅

5+^e|С дополнительным оборудованием

|<<employees.adoc#identity-cards,Идентификация сотрудника по карте>>
|❌
|❌
|✅ (покупается отдельно)
|✅

|<<stock.adoc#barcodes,Штрихкоды>>
|❌
|❌
|✅ (покупается отдельно)
|✅

|<<postomat.adoc#acceptance-in-launderette,Модуль стирки>>
|❌
|❌
|✅ (покупается отдельно)
|✅

|<<postomat.adoc#postamat,Постоматы выдачи\сдачи в стирку>>
|❌
|❌
|❌
|✅

5+^e|Интеграции

|<<import.adoc#import-stock-incomes,Загрузка поступлений в формате XML(1C)>>
|❌
|❌
|✅
|✅

|https://doc.qsolution.ru/api/v1/common.html[Доступ к API]
|❌
|❌
|✅ (при размещении на QS:Облако)
|✅
|===

== Рекомендуемая последовательность ввода данных

. Ввод справочных данных
.. В справочнике <<organization.adoc#organizations,«Организации»>> изменить название своей организации.
.. В справочнике <<organization.adoc#subdivisions,«Подразделения»>> создать подразделения, за которыми будут закреплены сотрудники. При желании детализации рабочего места, можно также создать <<organization.adoc#departments,отделы>>.
.. Заполняем <<regulations.adoc#norms,нормы выдачи>> на предприятии по профессиям, предварительно можно заполнить справочник <<regulations.adoc#protection-tools,«Номенклатура нормы»>>, если список выдаваемых СИЗ известен заранее, если нет, можно его заполнять в процессе ввода норм. Нормы выдачи можно вводить с привязкой к <<regulations.adoc#regulation-doc,нормативному документу>>, для этого предварительно нужно его создать.
.. Заполняем справочник <<organization.adoc#posts,должностей>>, при привязке нормы вручную сотрудникам этот шаг можно пропустить.
.. Вводим <<employees.adoc#employees,личные карточки учета выдачи СИЗ>> на сотрудников, которым необходимо будет получать спецодежду. Или <<import.adoc#employees-excel-import,загружаем сотрудников из Excel>>, в этом случае можно пропустить создание (подразделений, отделов и должностей) они могут быть созданы автоматически при создании сотрудников.
.. Привязываем сотрудников к нормам выдачи, либо вручную, либо по должности.
.. Если сотрудникам уже выдавалась спецодежда, вводим даты предыдущих выдач через функцию <<employees.adoc#issue-siz,установка даты выдачи>>.
.. Если планируется работать с несколькими складами, нужно их создать в справочнике <<stock.adoc#warehouses,«Склады»>>.
. Ввод данных учета
.. Если введены все данные по сотрудникам, можно рассчитать потребность в спецодежде через отчет <<reports.adoc#request-sheet,«Заявка на спецодежду»>>.
.. Внесите текущие остатки на складе через ввод <<stock-documents.adoc#stock-income,документа поступления>>, если остатков нет необходимо внести поступления. При вводе поступления можно заполнить справочник <<stock.adoc#nomenclatures,«Номенклатуры»>>.
.. <<employees.adoc#issue-siz,Выдача спецодежды>> сотрудникам.
.. По необходимости <<stock-documents.adoc#employee-return,возврат>> или <<stock-documents.adoc#writeoff,списание>> спецодежды.
