= Склады и номенклатура
:experimental:

[#warehouses]
== Склады

NOTE: Функциональность доступна только в редакции "Предприятие"

Вы можете вести учет по нескольким складам в одной базе. Создать новый склад можно в menu:Справочники[Склады]. Для корректного ведения учета в базе должен быть создан хотя бы один склад. 

TIP: Если в справочнике только один склад, программа автоматически будет проставлять его во все новые документы. Вы так же можете настроить автоматическое заполнение склада для своего пользователя в <<settings.adoc#user-settings,настройках>>.

Подразделения организации можно привязывать к определённым складам menu:Справочники[Подразделения], в этом случае при выдачи спецодежды сотруднику, склад будет автоматически проставлен, в зависимости от подразделения сотрудника. А так же в карточке сотрудника на вкладке «Спецодежда» будет отображаться не общее количество доступной спецодежды, а только на складе подразделения. 

== Типы номенклатуры

[#nomenclatures]
== Номенклатура
== Единицы измерения
== Размеры спецодежды