= Технические подробности

== Файл конфигурации

Некоторые настроки программы такие как список подключений к базе данных, хранятся для каждого пользователя операционной системы в конфигурационном файле.
Windows:: [path]_<домашний каталог пользователя>\AppData\Roaming\workwear.ini_ 
Linux:: [path]_<домашний каталог пользователя>/.config/workwear.ini_.
При необходимости его можно редактировать вручную или перенести с одного компьютера на другой.


.Пример файла workwear.ini
[source,ini]
----
[Login0]
UserLogin = demo
Server = demo.qsolution.ru
ConnectionName = Демонстрационная база
Type = 0
Account = 
DataBase = workwear
[Default]
ConnectionName = Рабочая
[Login1]
ConnectionName = Рабочая
Server = sql.qsolution.ru
Type = 0
Account = 
DataBase = workwear_work
----

Программа по умолчанию отправляет анонимную статистику по количеству использования различных функций программы, для определения основных потребностей наших пользователей. Если вы по какой-то причине не хотите отправлять статистику, отправку можно отключить добавив в файл параметр DoNotTrack.

.Пример секции отключающий телеметрию
[source,ini]
----
[Application]
DoNotTrack = true
----