= Ручной ввод данных
:experimental:

Начнем с подготовки базы вручную. Сначала создадим структуру организации и нормы выдачи, затем внесем сотрудников и прошлые выдачи, а в завершение введем складские остатки.

== Структура организации

Сначала определим, как представить в системе структуру организации.

В «QS: Спецодежда» используется следующая иерархия:

----
Организация
  └─ Подразделения
       └─ Отдел
            └─ Должности
                 └─ Сотрудники
----

Подразделения могут иметь несколько уровней вложенности. При этом любой уровень структуры можно пропустить.

Для небольшой организации структура может быть очень простой. В минимальном варианте можно вообще не создавать подразделения и должности, а назначать нормы непосредственно сотрудникам.

Для большинства предприятий все же рекомендуется завести хотя бы должности, поскольку нормы удобно привязывать именно к ним.

Если для одинаковых должностей нормы отличаются в зависимости от места работы, рекомендуется также использовать подразделения. Это позволяет однозначно определить, где работает сотрудник, и упрощает дальнейшую настройку.

Подразделения особенно важны, если на предприятии несколько складов: склады можно связывать с подразделениями, а кладовщиков — со складами.

=== Нужно ли использовать отделы

Поле «Отдел» является отдельным уровнем структуры, но использовать его необязательно. Во многих случаях всю иерархию можно построить только через подразделения.

На практике отдельное поле «Отдел» удобно использовать для самого нижнего уровня структуры, например для бригад или внутрицеховых групп. Это может упростить подготовку коллективных выдач.

Иногда такой подход помогает и при работе с нормами. Например, вместо создания множества одинаковых должностей для каждой бригады можно оставить одну должность в подразделении, а дополнительную детализацию перенести в отделы.

При этом отделы не следует использовать для параллельной группировки сотрудников.

Если требуется объединить, например, всех электриков из разных подразделений или сотрудников, участвующих в одном проекте, для этого предназначены группы сотрудников.

=== Можно не создавать структуру заранее

При ручном вводе необязательно сначала полностью формировать структуру организации.

Можно сразу начать создавать карточки сотрудников. При выборе должности, отдела или подразделения, если нужного значения еще нет, его можно создать непосредственно в процессе ввода.

Такой вариант удобен для небольших организаций или в ситуациях, когда структура уточняется по мере переноса данных.

== Нормы выдачи

После структуры организации рекомендуется настроить нормы выдачи.

На небольшом предприятии с несколькими нормами можно создать отдельную норму для каждой должности или даже для конкретных сотрудников. При небольшом объеме данных такой подход не создает проблем.

На крупных предприятиях нормы лучше организовать заранее, чтобы в дальнейшем их было проще поддерживать и изменять.

Практически удобно разделять нормы на несколько групп:

* нормы по должностям;
* общие нормы на ДСИЗ и другие СИЗ, которые выдаются большому количеству сотрудников;
* отдельные нормы на дополнительные условия, допуски и особенности работы.

Итоговая потребность сотрудника может формироваться сразу из нескольких примененных норм.

Например, сотруднику одновременно могут быть назначены:

* основная норма по должности;
* общая норма ДСИЗ;
* дополнительная норма для работ на высоте.

Такой подход требует немного больше настройки на старте, но значительно упрощает дальнейшее сопровождение.

Например, если предприятие меняет общую норму ДСИЗ, достаточно изменить ее один раз. Если же ДСИЗ включены непосредственно во множество должностных норм, одинаковые изменения придется выполнять во всех этих нормах.

Это особенно важно для крупных предприятий, где со временем могут появляться уникальные нормы, созданные для отдельных сотрудников или подразделений.

Если несколько разных должностей фактически получают одинаковый набор СИЗ, рекомендуется использовать одну норму и добавить в нее все подходящие должности.

Если все же требуется создать несколько похожих норм, существующую норму можно скопировать через контекстное меню в журнале норм выдачи и изменить только отличающиеся позиции.

=== Номенклатура в нормах

На этапе первоначального заполнения достаточно создать необходимую номенклатуру нормы и по возможности сразу указать тип номенклатуры.

Тип номенклатуры используется, в частности, при работе с размерами.

Для дерматологических СИЗ рекомендуется сразу установить соответствующий признак. Если известно, что номенклатура будет выдаваться через дозаторы, это также можно указать на этапе создания.

Остальные параметры можно настраивать позже по мере необходимости.

В результате этого этапа в системе должны быть созданы основные нормы предприятия и определены должности, которым они соответствуют.

== Карточки сотрудников

Следующий этап — создание сотрудников.

Сотрудник является центральной сущностью оперативного учета: к нему привязываются нормы, потребности, размеры, прошлые и текущие выдачи.

Минимально для создания сотрудника достаточно указать ФИО. Но для полноценной работы рекомендуется также вносить табельный номер, дату приема и другую доступную кадровую информацию.

Табельный номер особенно удобен для поиска сотрудника при выдаче.

При необходимости к карточке можно добавить фотографию. Она может использоваться для дополнительной идентификации сотрудника на складе.

=== Должность и подразделение

Если структура была настроена так, что отдельная должность соответствует конкретной единице штатного расписания, при создании сотрудника достаточно выбрать должность. Подразделение и отдел будут заполнены автоматически из нее.

Если используются общие должности для разных подразделений, подразделение сотрудника указывается отдельно.

=== Применение норм

Если нормы уже привязаны к должностям, при выборе должности программа предложит применить к сотруднику подходящие нормы.

При необходимости нормы можно назначить вручную на вкладке «Примененные нормы».

После применения одной или нескольких норм на вкладке «Спецодежда по нормам» появляется итоговая потребность сотрудника.

Если данные переносятся из бумажной карточки, на этом этапе удобно сверить рассчитанную системой потребность с тем, что указано в существующей карточке сотрудника.

== Ввод прошлых выдач

При вводе системы в эксплуатацию на действующем предприятии большинство сотрудников уже имеют ранее выданные СИЗ.

Чтобы система корректно рассчитывала следующие даты получения, прошлые выдачи рекомендуется перенести в карточки сотрудников.

Для этого на вкладке «Спецодежда по нормам» используйте кнопку btn:[Ручные операции выдачи].

Ручные операции позволяют зафиксировать прошлую выдачу без создания складского движения.

Минимально необходимо указать дату выдачи. На основании срока эксплуатации, заданного в норме, программа рассчитает дату окончания носки.

Если разные предметы были выданы сотруднику в разные даты, для одной потребности можно создать несколько ручных операций.

Если выданную ранее продукцию в дальнейшем планируется возвращать на склад, рекомендуется дополнительно указать конкретную складскую номенклатуру, размер и другие характеристики. При необходимости можно также присвоить штрихкод.

Если данные нужны только для контроля сроков эксплуатации, достаточно информации о датах получения и списания.

=== Размеры сотрудника

При переносе бумажных карточек рекомендуется сразу внести размеры одежды, обуви и других СИЗ на вкладке «Размеры».

Размеры используются системой при подборе спецодежды для выдачи и могут применяться при прогнозировании закупок по размерным рядам.

Настройку размерных сеток и типов номенклатуры рассмотрим отдельно.

== Ввод складских остатков

После создания сотрудников и переноса истории выдач можно переходить к наполнению склада.

Если предприятие уже работает, на момент ввода системы в эксплуатацию обычно имеются остатки ранее закупленной спецодежды.

Ввод начальных остатков выполняется тем же механизмом, что и обычное поступление: через складской документ «Поступление на склад».

=== Номенклатура нормы и складская номенклатура

В «QS: Спецодежда» используются два разных вида номенклатуры.

Номенклатура нормы:: обобщенная позиция, которая используется при составлении норм выдачи
Складская номенклатура:: конкретная продукция, по которой ведется складской учет и которая обычно соответствует наименованиям в накладных и других учетных документах

Эти сущности связаны по принципу «многие ко многим».

Одна складская позиция может подходить под несколько разных строк норм. И наоборот, одну позицию нормы можно обеспечивать несколькими моделями, производителями или вариантами продукции.

Например, под одну строку нормы «Костюм для защиты от общих производственных загрязнений» могут подходить несколько конкретных моделей костюмов, находящихся на складе.

При ручном вводе данных обычно нет необходимости заранее полностью заполнять справочник складской номенклатуры. Новые позиции можно создавать непосредственно в документе поступления по мере ввода остатков.

=== Как учитываются остатки

Складской учет ведется не только в разрезе номенклатуры.

Дополнительно учитываются размер и рост. По смыслу это близко к характеристикам номенклатуры в 1С.

Отдельным измерением является процент износа. Продукция с разным процентом износа учитывается раздельно.

Например, остаток одной и той же номенклатуры может одновременно содержать новые изделия с 0% износа и ранее использовавшиеся изделия с 50% износа.

В системе также поддерживается учет по собственникам. Этот механизм рассмотрим отдельно.

=== Быстрый ввод размеров

Если требуется внести большое количество одной номенклатуры разных размеров, удобно использовать команду btn:[Добавить размеры].

Сначала в документ добавляется одна позиция номенклатуры, после чего выбираются необходимые размеры и указывается количество по каждому из них.

Это значительно быстрее, чем создавать каждую строку документа вручную.

Необязательно вводить все остатки одним документом. На практике удобнее разделять их на логические части, чтобы было проще проверять данные.

Итоговый результат можно проверить в журнале «Остатки по складу».

== Результат ручного ввода данных

После выполнения этих этапов в системе должны быть:

* сформирована структура организации;
* созданы нормы выдачи;
* внесены сотрудники;
* рассчитаны их потребности;
* перенесены необходимые прошлые выдачи;
* внесены размеры сотрудников;
* сформированы складские остатки.

После этого можно переходить к оперативной работе: персональным и коллективным выдачам, возвратам, контролю обеспеченности и другим ежедневным операциям.
