
// This file has been generated by the GUI designer. Do not modify.
namespace Workwear.Journal.Filter.Views.Regulations
{
	public partial class ProtectionToolsFilterView
	{
		private global::Gamma.GtkWidgets.yCheckButton ycheckOnlyDermal;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Workwear.Journal.Filter.Views.Regulations.ProtectionToolsFilterView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Workwear.Journal.Filter.Views.Regulations.ProtectionToolsFilterView";
			// Container child Workwear.Journal.Filter.Views.Regulations.ProtectionToolsFilterView.Gtk.Container+ContainerChild
			this.ycheckOnlyDermal = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckOnlyDermal.CanFocus = true;
			this.ycheckOnlyDermal.Name = "ycheckOnlyDermal";
			this.ycheckOnlyDermal.Label = global::Mono.Unix.Catalog.GetString("Только дерматологические");
			this.ycheckOnlyDermal.DrawIndicator = true;
			this.ycheckOnlyDermal.UseUnderline = true;
			this.Add(this.ycheckOnlyDermal);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
