
// This file has been generated by the GUI designer. Do not modify.
namespace Workwear.Views.Visits
{
	public partial class IssuanceRequestView
	{
		private global::Gtk.VBox dialog1_VBox;

		private global::Gtk.HBox hbox4;

		private global::Gamma.GtkWidgets.yButton buttonSave;

		private global::Gamma.GtkWidgets.yButton buttonCancel;

		private global::Gamma.GtkWidgets.yButton buttonColorsLegend;

		private global::Gamma.GtkWidgets.yNotebook tabs;

		private global::Gtk.Table table1;

		private global::Gamma.Widgets.yEnumComboBox enumStatus;

		private global::Gtk.ScrolledWindow GtkScrolledWindowComments;

		private global::Gamma.GtkWidgets.yTextView ytextviewComment;

		private global::Gtk.Label label_number;

		private global::Gtk.Label label_receipt_date;

		private global::Gtk.Label label_user;

		private global::QS.Widgets.GtkUI.DatePicker receiptDate;

		private global::Gtk.Label ylabelComment;

		private global::Gamma.GtkWidgets.yLabel ylabelId;

		private global::Gamma.GtkWidgets.yLabel ylabelStatus;

		private global::Gamma.GtkWidgets.yLabel ylabelUser;

		private global::Gtk.Label label9;

		private global::Gamma.GtkWidgets.yVBox yvbox7;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewEmployees;

		private global::Gamma.GtkWidgets.yHBox yhbox3;

		private global::QSWidgetLib.MenuButton buttonAdd;

		private global::Gamma.GtkWidgets.yButton buttonRemove;

		private global::Gtk.Label label1;

		private global::Gamma.GtkWidgets.yVBox yvbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewExpense;

		private global::Gamma.GtkWidgets.yHBox yhbox2;

		private global::Gamma.GtkWidgets.yLabel ylabelWarehouse;

		private global::Gamma.Widgets.ySpecComboBox yspeccomboboxWarehouse;

		private global::Gamma.GtkWidgets.yHBox yhbox1;

		private global::Gamma.GtkWidgets.yButton buttonCreateExpense;

		private global::Gamma.GtkWidgets.yButton buttonRemoveExpense;

		private global::Gamma.GtkWidgets.yButton buttonAddExpense;

		private global::Gtk.Label label2;

		private global::Workwear.Views.Visits.IssuanceRequestEmployeeCardItemsView issuancerequestemployeecarditemsview1;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Workwear.Views.Visits.IssuanceRequestView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Workwear.Views.Visits.IssuanceRequestView";
			// Container child Workwear.Views.Visits.IssuanceRequestView.Gtk.Container+ContainerChild
			this.dialog1_VBox = new global::Gtk.VBox();
			this.dialog1_VBox.Name = "dialog1_VBox";
			this.dialog1_VBox.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonSave = new global::Gamma.GtkWidgets.yButton();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w1;
			this.hbox4.Add(this.buttonSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gamma.GtkWidgets.yButton();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Отменить");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w3;
			this.hbox4.Add(this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonColorsLegend = new global::Gamma.GtkWidgets.yButton();
			this.buttonColorsLegend.TooltipMarkup = "Цветовая легенда";
			this.buttonColorsLegend.CanFocus = true;
			this.buttonColorsLegend.Name = "buttonColorsLegend";
			this.buttonColorsLegend.UseUnderline = true;
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Workwear.icon.buttons.legend.png");
			this.buttonColorsLegend.Image = w5;
			this.hbox4.Add(this.buttonColorsLegend);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonColorsLegend]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.dialog1_VBox.Add(this.hbox4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox[this.hbox4]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.tabs = new global::Gamma.GtkWidgets.yNotebook();
			this.tabs.CanFocus = true;
			this.tabs.Name = "tabs";
			this.tabs.CurrentPage = 0;
			// Container child tabs.Gtk.Notebook+NotebookChild
			this.table1 = new global::Gtk.Table(((uint)(5)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.enumStatus = new global::Gamma.Widgets.yEnumComboBox();
			this.enumStatus.Name = "enumStatus";
			this.enumStatus.ShowSpecialStateAll = false;
			this.enumStatus.ShowSpecialStateNot = false;
			this.enumStatus.UseShortTitle = false;
			this.enumStatus.DefaultFirst = false;
			this.table1.Add(this.enumStatus);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.enumStatus]));
			w8.TopAttach = ((uint)(3));
			w8.BottomAttach = ((uint)(4));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindowComments = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindowComments.Name = "GtkScrolledWindowComments";
			this.GtkScrolledWindowComments.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindowComments.Gtk.Container+ContainerChild
			this.ytextviewComment = new global::Gamma.GtkWidgets.yTextView();
			this.ytextviewComment.CanFocus = true;
			this.ytextviewComment.Name = "ytextviewComment";
			this.ytextviewComment.AcceptsTab = false;
			this.ytextviewComment.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindowComments.Add(this.ytextviewComment);
			this.table1.Add(this.GtkScrolledWindowComments);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindowComments]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.label_number = new global::Gtk.Label();
			this.label_number.Name = "label_number";
			this.label_number.Xalign = 1F;
			this.label_number.LabelProp = global::Mono.Unix.Catalog.GetString("Номер:");
			this.table1.Add(this.label_number);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.label_number]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label_receipt_date = new global::Gtk.Label();
			this.label_receipt_date.Name = "label_receipt_date";
			this.label_receipt_date.Xalign = 1F;
			this.label_receipt_date.LabelProp = global::Mono.Unix.Catalog.GetString("Дата поступления заявки:");
			this.table1.Add(this.label_receipt_date);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.label_receipt_date]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label_user = new global::Gtk.Label();
			this.label_user.Name = "label_user";
			this.label_user.Xalign = 1F;
			this.label_user.LabelProp = global::Mono.Unix.Catalog.GetString("Пользователь:");
			this.table1.Add(this.label_user);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.label_user]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.receiptDate = new global::QS.Widgets.GtkUI.DatePicker();
			this.receiptDate.Events = ((global::Gdk.EventMask)(256));
			this.receiptDate.Name = "receiptDate";
			this.receiptDate.WithTime = false;
			this.receiptDate.HideCalendarButton = false;
			this.receiptDate.Date = new global::System.DateTime(0);
			this.receiptDate.IsEditable = true;
			this.receiptDate.AutoSeparation = true;
			this.receiptDate.HideButtonClearDate = false;
			this.table1.Add(this.receiptDate);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.receiptDate]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelComment = new global::Gtk.Label();
			this.ylabelComment.Name = "ylabelComment";
			this.ylabelComment.Xalign = 1F;
			this.ylabelComment.Yalign = 0F;
			this.ylabelComment.LabelProp = global::Mono.Unix.Catalog.GetString("Комментарий:");
			this.table1.Add(this.ylabelComment);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelComment]));
			w15.TopAttach = ((uint)(4));
			w15.BottomAttach = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelId = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelId.Name = "ylabelId";
			this.ylabelId.LabelProp = global::Mono.Unix.Catalog.GetString("ylabel4");
			this.table1.Add(this.ylabelId);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelId]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelStatus = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelStatus.Name = "ylabelStatus";
			this.ylabelStatus.Xalign = 1F;
			this.ylabelStatus.LabelProp = global::Mono.Unix.Catalog.GetString("Статус:");
			this.table1.Add(this.ylabelStatus);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelStatus]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelUser = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelUser.Name = "ylabelUser";
			this.ylabelUser.LabelProp = global::Mono.Unix.Catalog.GetString("ylabel5");
			this.table1.Add(this.ylabelUser);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelUser]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			this.tabs.Add(this.table1);
			// Notebook tab
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Основное");
			this.tabs.SetTabLabel(this.table1, this.label9);
			this.label9.ShowAll();
			// Container child tabs.Gtk.Notebook+NotebookChild
			this.yvbox7 = new global::Gamma.GtkWidgets.yVBox();
			this.yvbox7.Name = "yvbox7";
			this.yvbox7.Spacing = 6;
			// Container child yvbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytreeviewEmployees = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewEmployees.CanFocus = true;
			this.ytreeviewEmployees.Name = "ytreeviewEmployees";
			this.GtkScrolledWindow.Add(this.ytreeviewEmployees);
			this.yvbox7.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.yvbox7[this.GtkScrolledWindow]));
			w21.Position = 0;
			// Container child yvbox7.Gtk.Box+BoxChild
			this.yhbox3 = new global::Gamma.GtkWidgets.yHBox();
			this.yhbox3.Name = "yhbox3";
			this.yhbox3.Spacing = 6;
			// Container child yhbox3.Gtk.Box+BoxChild
			this.buttonAdd = new global::QSWidgetLib.MenuButton();
			this.buttonAdd.CanFocus = true;
			this.buttonAdd.Name = "buttonAdd";
			this.buttonAdd.UseUnderline = true;
			this.buttonAdd.UseMarkup = false;
			this.buttonAdd.LabelXAlign = 0F;
			this.buttonAdd.Label = global::Mono.Unix.Catalog.GetString("Добавить");
			global::Gtk.Image w22 = new global::Gtk.Image();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonAdd.Image = w22;
			this.yhbox3.Add(this.buttonAdd);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.yhbox3[this.buttonAdd]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child yhbox3.Gtk.Box+BoxChild
			this.buttonRemove = new global::Gamma.GtkWidgets.yButton();
			this.buttonRemove.Sensitive = false;
			this.buttonRemove.CanFocus = true;
			this.buttonRemove.Name = "buttonRemove";
			this.buttonRemove.UseUnderline = true;
			this.buttonRemove.Label = global::Mono.Unix.Catalog.GetString("Удалить");
			global::Gtk.Image w24 = new global::Gtk.Image();
			w24.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.buttonRemove.Image = w24;
			this.yhbox3.Add(this.buttonRemove);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.yhbox3[this.buttonRemove]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.yvbox7.Add(this.yhbox3);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.yvbox7[this.yhbox3]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.tabs.Add(this.yvbox7);
			global::Gtk.Notebook.NotebookChild w27 = ((global::Gtk.Notebook.NotebookChild)(this.tabs[this.yvbox7]));
			w27.Position = 1;
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Сотрудники");
			this.tabs.SetTabLabel(this.yvbox7, this.label1);
			this.label1.ShowAll();
			// Container child tabs.Gtk.Notebook+NotebookChild
			this.yvbox1 = new global::Gamma.GtkWidgets.yVBox();
			this.yvbox1.Name = "yvbox1";
			this.yvbox1.Spacing = 6;
			// Container child yvbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.ytreeviewExpense = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewExpense.CanFocus = true;
			this.ytreeviewExpense.Name = "ytreeviewExpense";
			this.GtkScrolledWindow1.Add(this.ytreeviewExpense);
			this.yvbox1.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.yvbox1[this.GtkScrolledWindow1]));
			w29.Position = 0;
			// Container child yvbox1.Gtk.Box+BoxChild
			this.yhbox2 = new global::Gamma.GtkWidgets.yHBox();
			this.yhbox2.Name = "yhbox2";
			this.yhbox2.Spacing = 6;
			// Container child yhbox2.Gtk.Box+BoxChild
			this.ylabelWarehouse = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelWarehouse.Name = "ylabelWarehouse";
			this.ylabelWarehouse.LabelProp = global::Mono.Unix.Catalog.GetString("Склад выдачи:");
			this.yhbox2.Add(this.ylabelWarehouse);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.yhbox2[this.ylabelWarehouse]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child yhbox2.Gtk.Box+BoxChild
			this.yspeccomboboxWarehouse = new global::Gamma.Widgets.ySpecComboBox();
			this.yspeccomboboxWarehouse.Name = "yspeccomboboxWarehouse";
			this.yspeccomboboxWarehouse.AddIfNotExist = false;
			this.yspeccomboboxWarehouse.DefaultFirst = false;
			this.yspeccomboboxWarehouse.ShowSpecialStateAll = false;
			this.yspeccomboboxWarehouse.ShowSpecialStateNot = false;
			this.yhbox2.Add(this.yspeccomboboxWarehouse);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.yhbox2[this.yspeccomboboxWarehouse]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.yvbox1.Add(this.yhbox2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.yvbox1[this.yhbox2]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child yvbox1.Gtk.Box+BoxChild
			this.yhbox1 = new global::Gamma.GtkWidgets.yHBox();
			this.yhbox1.Name = "yhbox1";
			this.yhbox1.Spacing = 6;
			// Container child yhbox1.Gtk.Box+BoxChild
			this.buttonCreateExpense = new global::Gamma.GtkWidgets.yButton();
			this.buttonCreateExpense.CanFocus = true;
			this.buttonCreateExpense.Name = "buttonCreateExpense";
			this.buttonCreateExpense.UseUnderline = true;
			this.buttonCreateExpense.Label = global::Mono.Unix.Catalog.GetString("Создать коллективную выдачу");
			global::Gtk.Image w33 = new global::Gtk.Image();
			w33.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonCreateExpense.Image = w33;
			this.yhbox1.Add(this.buttonCreateExpense);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.yhbox1[this.buttonCreateExpense]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child yhbox1.Gtk.Box+BoxChild
			this.buttonRemoveExpense = new global::Gamma.GtkWidgets.yButton();
			this.buttonRemoveExpense.CanFocus = true;
			this.buttonRemoveExpense.Name = "buttonRemoveExpense";
			this.buttonRemoveExpense.UseUnderline = true;
			this.buttonRemoveExpense.Label = global::Mono.Unix.Catalog.GetString("Отвязать");
			this.yhbox1.Add(this.buttonRemoveExpense);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.yhbox1[this.buttonRemoveExpense]));
			w35.PackType = ((global::Gtk.PackType)(1));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			// Container child yhbox1.Gtk.Box+BoxChild
			this.buttonAddExpense = new global::Gamma.GtkWidgets.yButton();
			this.buttonAddExpense.CanFocus = true;
			this.buttonAddExpense.Name = "buttonAddExpense";
			this.buttonAddExpense.UseUnderline = true;
			this.buttonAddExpense.Label = global::Mono.Unix.Catalog.GetString("Привязать");
			this.yhbox1.Add(this.buttonAddExpense);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.yhbox1[this.buttonAddExpense]));
			w36.PackType = ((global::Gtk.PackType)(1));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.yvbox1.Add(this.yhbox1);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.yvbox1[this.yhbox1]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			this.tabs.Add(this.yvbox1);
			global::Gtk.Notebook.NotebookChild w38 = ((global::Gtk.Notebook.NotebookChild)(this.tabs[this.yvbox1]));
			w38.Position = 2;
			// Notebook tab
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Выдачи");
			this.tabs.SetTabLabel(this.yvbox1, this.label2);
			this.label2.ShowAll();
			// Container child tabs.Gtk.Notebook+NotebookChild
			this.issuancerequestemployeecarditemsview1 = new global::Workwear.Views.Visits.IssuanceRequestEmployeeCardItemsView();
			this.issuancerequestemployeecarditemsview1.Events = ((global::Gdk.EventMask)(256));
			this.issuancerequestemployeecarditemsview1.Name = "issuancerequestemployeecarditemsview1";
			this.tabs.Add(this.issuancerequestemployeecarditemsview1);
			global::Gtk.Notebook.NotebookChild w39 = ((global::Gtk.Notebook.NotebookChild)(this.tabs[this.issuancerequestemployeecarditemsview1]));
			w39.Position = 3;
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Потребности");
			this.tabs.SetTabLabel(this.issuancerequestemployeecarditemsview1, this.label3);
			this.label3.ShowAll();
			this.dialog1_VBox.Add(this.tabs);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox[this.tabs]));
			w40.Position = 1;
			this.Add(this.dialog1_VBox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.buttonColorsLegend.Clicked += new global::System.EventHandler(this.OnButtonColorsLegendClicked);
			this.buttonRemove.Clicked += new global::System.EventHandler(this.OnButtonRemoveItemClicked);
			this.buttonCreateExpense.Clicked += new global::System.EventHandler(this.OnButtonCreateExpenseClicked);
			this.buttonAddExpense.Clicked += new global::System.EventHandler(this.OnButtonAddExpenseClicked);
			this.buttonRemoveExpense.Clicked += new global::System.EventHandler(this.OnButtonRemoveExpenseClicked);
		}
	}
}
