
// This file has been generated by the GUI designer. Do not modify.
namespace workwear.Views.Communications
{
	public partial class ClaimsView
	{
		private global::Gamma.GtkWidgets.yHBox yhbox1;

		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gamma.GtkWidgets.yTreeView ytreeClaims;

		private global::Gamma.GtkWidgets.yVBox yvbox2;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gamma.GtkWidgets.yTreeView ytreeClaimMessages;

		private global::Gamma.GtkWidgets.yVBox yvbox3;

		private global::Gamma.GtkWidgets.yHBox yhbox2;

		private global::Gamma.GtkWidgets.yEntry yentryMessage;

		private global::Gamma.GtkWidgets.yButton ybuttonSend;

		private global::Gamma.GtkWidgets.yHBox yhbox3;

		private global::Gamma.GtkWidgets.yLabel ylabelStatusClaim;

		private global::Gamma.Widgets.yEnumComboBox yenumcombobox2;

		private global::Gamma.GtkWidgets.yButton ybuttonChangeStatus;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget workwear.Views.Communications.ClaimsView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "workwear.Views.Communications.ClaimsView";
			// Container child workwear.Views.Communications.ClaimsView.Gtk.Container+ContainerChild
			this.yhbox1 = new global::Gamma.GtkWidgets.yHBox();
			this.yhbox1.Name = "yhbox1";
			this.yhbox1.Spacing = 6;
			// Container child yhbox1.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.ytreeClaims = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeClaims.CanFocus = true;
			this.ytreeClaims.Name = "ytreeClaims";
			this.scrolledwindow2.Add(this.ytreeClaims);
			this.yhbox1.Add(this.scrolledwindow2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.yhbox1[this.scrolledwindow2]));
			w2.Position = 0;
			// Container child yhbox1.Gtk.Box+BoxChild
			this.yvbox2 = new global::Gamma.GtkWidgets.yVBox();
			this.yvbox2.Name = "yvbox2";
			this.yvbox2.Spacing = 6;
			// Container child yvbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.ytreeClaimMessages = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeClaimMessages.Sensitive = false;
			this.ytreeClaimMessages.CanFocus = true;
			this.ytreeClaimMessages.Name = "ytreeClaimMessages";
			this.ytreeClaimMessages.HeadersVisible = false;
			this.scrolledwindow1.Add(this.ytreeClaimMessages);
			this.yvbox2.Add(this.scrolledwindow1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.yvbox2[this.scrolledwindow1]));
			w4.Position = 0;
			// Container child yvbox2.Gtk.Box+BoxChild
			this.yvbox3 = new global::Gamma.GtkWidgets.yVBox();
			this.yvbox3.Name = "yvbox3";
			this.yvbox3.Spacing = 6;
			// Container child yvbox3.Gtk.Box+BoxChild
			this.yhbox2 = new global::Gamma.GtkWidgets.yHBox();
			this.yhbox2.Name = "yhbox2";
			this.yhbox2.Spacing = 6;
			// Container child yhbox2.Gtk.Box+BoxChild
			this.yentryMessage = new global::Gamma.GtkWidgets.yEntry();
			this.yentryMessage.CanFocus = true;
			this.yentryMessage.Name = "yentryMessage";
			this.yentryMessage.IsEditable = true;
			this.yentryMessage.InvisibleChar = '•';
			this.yhbox2.Add(this.yentryMessage);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.yhbox2[this.yentryMessage]));
			w5.Position = 0;
			// Container child yhbox2.Gtk.Box+BoxChild
			this.ybuttonSend = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonSend.CanFocus = true;
			this.ybuttonSend.Name = "ybuttonSend";
			this.ybuttonSend.UseUnderline = true;
			this.ybuttonSend.Label = global::Mono.Unix.Catalog.GetString("Отправить");
			global::Gtk.Image w6 = new global::Gtk.Image();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "stock_mail-send", global::Gtk.IconSize.Menu);
			this.ybuttonSend.Image = w6;
			this.yhbox2.Add(this.ybuttonSend);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.yhbox2[this.ybuttonSend]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.yvbox3.Add(this.yhbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.yvbox3[this.yhbox2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child yvbox3.Gtk.Box+BoxChild
			this.yhbox3 = new global::Gamma.GtkWidgets.yHBox();
			this.yhbox3.Name = "yhbox3";
			this.yhbox3.Spacing = 6;
			// Container child yhbox3.Gtk.Box+BoxChild
			this.ylabelStatusClaim = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelStatusClaim.Name = "ylabelStatusClaim";
			this.ylabelStatusClaim.LabelProp = global::Mono.Unix.Catalog.GetString("Статус обращения");
			this.yhbox3.Add(this.ylabelStatusClaim);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.yhbox3[this.ylabelStatusClaim]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child yhbox3.Gtk.Box+BoxChild
			this.yenumcombobox2 = new global::Gamma.Widgets.yEnumComboBox();
			this.yenumcombobox2.Name = "yenumcombobox2";
			this.yenumcombobox2.ShowSpecialStateAll = false;
			this.yenumcombobox2.ShowSpecialStateNot = false;
			this.yenumcombobox2.UseShortTitle = false;
			this.yenumcombobox2.DefaultFirst = false;
			this.yhbox3.Add(this.yenumcombobox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.yhbox3[this.yenumcombobox2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child yhbox3.Gtk.Box+BoxChild
			this.ybuttonChangeStatus = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonChangeStatus.CanFocus = true;
			this.ybuttonChangeStatus.Name = "ybuttonChangeStatus";
			this.ybuttonChangeStatus.UseUnderline = true;
			this.ybuttonChangeStatus.Label = global::Mono.Unix.Catalog.GetString("Изменить");
			this.yhbox3.Add(this.ybuttonChangeStatus);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.yhbox3[this.ybuttonChangeStatus]));
			w11.Position = 2;
			this.yvbox3.Add(this.yhbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.yvbox3[this.yhbox3]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.yvbox2.Add(this.yvbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.yvbox2[this.yvbox3]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.yhbox1.Add(this.yvbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.yhbox1[this.yvbox2]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.Add(this.yhbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
