
// This file has been generated by the GUI designer. Do not modify.
namespace Workwear.ReportParameters.Views
{
	public partial class WearCardsReportView
	{
		private global::Gtk.VBox vbox1;

		private global::Gamma.GtkWidgets.yTable ytable1;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonOnlyWithoutNorms;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonOnlyWorking;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::Gamma.GtkWidgets.yLabel ylabel2;

		private global::Gamma.GtkWidgets.yButton ybuttonRun;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Workwear.ReportParameters.Views.WearCardsReportView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Workwear.ReportParameters.Views.WearCardsReportView";
			// Container child Workwear.ReportParameters.Views.WearCardsReportView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ytable1 = new global::Gamma.GtkWidgets.yTable();
			this.ytable1.Name = "ytable1";
			this.ytable1.NRows = ((uint)(2));
			this.ytable1.NColumns = ((uint)(2));
			this.ytable1.RowSpacing = ((uint)(6));
			this.ytable1.ColumnSpacing = ((uint)(6));
			// Container child ytable1.Gtk.Table+TableChild
			this.ycheckbuttonOnlyWithoutNorms = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonOnlyWithoutNorms.CanFocus = true;
			this.ycheckbuttonOnlyWithoutNorms.Name = "ycheckbuttonOnlyWithoutNorms";
			this.ycheckbuttonOnlyWithoutNorms.Label = "";
			this.ycheckbuttonOnlyWithoutNorms.DrawIndicator = true;
			this.ycheckbuttonOnlyWithoutNorms.UseUnderline = true;
			this.ytable1.Add(this.ycheckbuttonOnlyWithoutNorms);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.ytable1[this.ycheckbuttonOnlyWithoutNorms]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.ycheckbuttonOnlyWorking = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonOnlyWorking.CanFocus = true;
			this.ycheckbuttonOnlyWorking.Name = "ycheckbuttonOnlyWorking";
			this.ycheckbuttonOnlyWorking.Label = "";
			this.ycheckbuttonOnlyWorking.DrawIndicator = true;
			this.ycheckbuttonOnlyWorking.UseUnderline = true;
			this.ytable1.Add(this.ycheckbuttonOnlyWorking);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.ytable1[this.ycheckbuttonOnlyWorking]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.Xalign = 0F;
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Только сотрудники без норм");
			this.ytable1.Add(this.ylabel1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.ytable1[this.ylabel1]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.ylabel2 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel2.Name = "ylabel2";
			this.ylabel2.Xalign = 0F;
			this.ylabel2.LabelProp = global::Mono.Unix.Catalog.GetString("Только работающие");
			this.ytable1.Add(this.ylabel2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.ytable1[this.ylabel2]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.ytable1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.ytable1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ybuttonRun = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonRun.CanFocus = true;
			this.ybuttonRun.Name = "ybuttonRun";
			this.ybuttonRun.UseUnderline = true;
			this.ybuttonRun.Label = global::Mono.Unix.Catalog.GetString("Сформировать отчет");
			this.vbox1.Add(this.ybuttonRun);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.ybuttonRun]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.ybuttonRun.Clicked += new global::System.EventHandler(this.OnYbuttonRunClicked);
		}
	}
}
