
// This file has been generated by the GUI designer. Do not modify.
namespace Workwear.ReportParameters.Views
{
	public partial class ChoiceProtectionToolsView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gamma.GtkWidgets.yButton ycheckbuttonChooseAll;

		private global::Gamma.GtkWidgets.yButton ycheckbuttonUnChooseAll;

		private global::Gtk.HBox hbox2;

		private global::Gamma.GtkWidgets.yImage yimage1;

		private global::Gamma.GtkWidgets.yEntry yentrySearch;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytreeChoiseProtectionTools;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Workwear.ReportParameters.Views.ChoiceProtectionToolsView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Workwear.ReportParameters.Views.ChoiceProtectionToolsView";
			// Container child Workwear.ReportParameters.Views.ChoiceProtectionToolsView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ycheckbuttonChooseAll = new global::Gamma.GtkWidgets.yButton();
			this.ycheckbuttonChooseAll.CanFocus = true;
			this.ycheckbuttonChooseAll.Name = "ycheckbuttonChooseAll";
			this.ycheckbuttonChooseAll.UseUnderline = true;
			this.ycheckbuttonChooseAll.Label = global::Mono.Unix.Catalog.GetString("Выделить всё");
			this.hbox1.Add(this.ycheckbuttonChooseAll);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ycheckbuttonChooseAll]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ycheckbuttonUnChooseAll = new global::Gamma.GtkWidgets.yButton();
			this.ycheckbuttonUnChooseAll.CanFocus = true;
			this.ycheckbuttonUnChooseAll.Name = "ycheckbuttonUnChooseAll";
			this.ycheckbuttonUnChooseAll.UseUnderline = true;
			this.ycheckbuttonUnChooseAll.Label = global::Mono.Unix.Catalog.GetString("Снять выделение");
			this.hbox1.Add(this.ycheckbuttonUnChooseAll);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ycheckbuttonUnChooseAll]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.yimage1 = new global::Gamma.GtkWidgets.yImage();
			this.yimage1.Name = "yimage1";
			this.yimage1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.Menu);
			this.hbox2.Add(this.yimage1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.yimage1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.yentrySearch = new global::Gamma.GtkWidgets.yEntry();
			this.yentrySearch.CanFocus = true;
			this.yentrySearch.Name = "yentrySearch";
			this.yentrySearch.IsEditable = true;
			this.yentrySearch.InvisibleChar = '•';
			this.hbox2.Add(this.yentrySearch);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.yentrySearch]));
			w5.Position = 1;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytreeChoiseProtectionTools = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeChoiseProtectionTools.WidthRequest = 400;
			this.ytreeChoiseProtectionTools.CanFocus = true;
			this.ytreeChoiseProtectionTools.Name = "ytreeChoiseProtectionTools";
			this.GtkScrolledWindow.Add(this.ytreeChoiseProtectionTools);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w8.Position = 2;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
