
// This file has been generated by the GUI designer. Do not modify.
namespace Workwear.ReportParameters.Views
{
	public partial class ProvisionReportView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Table table1;

		private global::Gamma.Widgets.yEnumComboBox comboIssueType;

		private global::Gamma.Widgets.yEnumComboBox comboReportType;

		private global::Gamma.GtkWidgets.yLabel labelIssueType;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonExcludeInVacation;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonGroupByNormAmount;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonGroupBySubdivision;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonShowSex;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonShowSize;

		private global::Gamma.GtkWidgets.yCheckButton ycheckShowEmployees;

		private global::Gamma.GtkWidgets.yCheckButton ycheckShowStock;

		private global::Gamma.GtkWidgets.yLabel ylabel5;

		private global::Gamma.GtkWidgets.yLabel ylabelExcludeInVacation;

		private global::Gamma.GtkWidgets.yLabel ylabelGroupByNormAmount;

		private global::Gtk.Label ylabelGroupBySubdivision;

		private global::Gamma.GtkWidgets.yLabel ylabelShowEmployees;

		private global::Gamma.GtkWidgets.yLabel ylabelShowSex;

		private global::Gamma.GtkWidgets.yLabel ylabelShowSize;

		private global::Gamma.GtkWidgets.yLabel ylabelShowStock;

		private global::Gtk.Expander expander1;

		private global::QS.Views.Control.ChoiceListView choiceprotectiontoolsview1;

		private global::Gtk.Label GtkLabel10;

		private global::Gtk.Expander expander2;

		private global::QS.Views.Control.ChoiceListView choicesubdivisionview1;

		private global::Gtk.Label GtkLabel14;

		private global::Gtk.Expander expanderEmployeeGroups;

		private global::QS.Views.Control.ChoiceListView choiceemployeegroupview1;

		private global::Gtk.Label GtkLabel18;

		private global::Gamma.GtkWidgets.yButton ybuttonRun;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Workwear.ReportParameters.Views.ProvisionReportView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Workwear.ReportParameters.Views.ProvisionReportView";
			// Container child Workwear.ReportParameters.Views.ProvisionReportView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(9)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.comboIssueType = new global::Gamma.Widgets.yEnumComboBox();
			this.comboIssueType.Name = "comboIssueType";
			this.comboIssueType.ShowSpecialStateAll = true;
			this.comboIssueType.ShowSpecialStateNot = false;
			this.comboIssueType.UseShortTitle = false;
			this.comboIssueType.DefaultFirst = false;
			this.table1.Add(this.comboIssueType);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.comboIssueType]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboReportType = new global::Gamma.Widgets.yEnumComboBox();
			this.comboReportType.Name = "comboReportType";
			this.comboReportType.ShowSpecialStateAll = false;
			this.comboReportType.ShowSpecialStateNot = false;
			this.comboReportType.UseShortTitle = false;
			this.comboReportType.DefaultFirst = true;
			this.table1.Add(this.comboReportType);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.comboReportType]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelIssueType = new global::Gamma.GtkWidgets.yLabel();
			this.labelIssueType.Name = "labelIssueType";
			this.labelIssueType.Xalign = 1F;
			this.labelIssueType.LabelProp = global::Mono.Unix.Catalog.GetString("Тип выдачи");
			this.table1.Add(this.labelIssueType);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.labelIssueType]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ycheckbuttonExcludeInVacation = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonExcludeInVacation.CanFocus = true;
			this.ycheckbuttonExcludeInVacation.Name = "ycheckbuttonExcludeInVacation";
			this.ycheckbuttonExcludeInVacation.Label = "";
			this.ycheckbuttonExcludeInVacation.DrawIndicator = true;
			this.ycheckbuttonExcludeInVacation.UseUnderline = true;
			this.table1.Add(this.ycheckbuttonExcludeInVacation);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.ycheckbuttonExcludeInVacation]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ycheckbuttonGroupByNormAmount = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonGroupByNormAmount.CanFocus = true;
			this.ycheckbuttonGroupByNormAmount.Name = "ycheckbuttonGroupByNormAmount";
			this.ycheckbuttonGroupByNormAmount.Label = "";
			this.ycheckbuttonGroupByNormAmount.DrawIndicator = true;
			this.ycheckbuttonGroupByNormAmount.UseUnderline = true;
			this.table1.Add(this.ycheckbuttonGroupByNormAmount);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.ycheckbuttonGroupByNormAmount]));
			w5.TopAttach = ((uint)(6));
			w5.BottomAttach = ((uint)(7));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ycheckbuttonGroupBySubdivision = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonGroupBySubdivision.CanFocus = true;
			this.ycheckbuttonGroupBySubdivision.Name = "ycheckbuttonGroupBySubdivision";
			this.ycheckbuttonGroupBySubdivision.Label = "";
			this.ycheckbuttonGroupBySubdivision.DrawIndicator = true;
			this.ycheckbuttonGroupBySubdivision.UseUnderline = true;
			this.table1.Add(this.ycheckbuttonGroupBySubdivision);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.ycheckbuttonGroupBySubdivision]));
			w6.TopAttach = ((uint)(5));
			w6.BottomAttach = ((uint)(6));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ycheckbuttonShowSex = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonShowSex.CanFocus = true;
			this.ycheckbuttonShowSex.Name = "ycheckbuttonShowSex";
			this.ycheckbuttonShowSex.Label = "";
			this.ycheckbuttonShowSex.DrawIndicator = true;
			this.ycheckbuttonShowSex.UseUnderline = true;
			this.table1.Add(this.ycheckbuttonShowSex);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.ycheckbuttonShowSex]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ycheckbuttonShowSize = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonShowSize.CanFocus = true;
			this.ycheckbuttonShowSize.Name = "ycheckbuttonShowSize";
			this.ycheckbuttonShowSize.Label = "";
			this.ycheckbuttonShowSize.DrawIndicator = true;
			this.ycheckbuttonShowSize.UseUnderline = true;
			this.table1.Add(this.ycheckbuttonShowSize);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.ycheckbuttonShowSize]));
			w8.TopAttach = ((uint)(4));
			w8.BottomAttach = ((uint)(5));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ycheckShowEmployees = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckShowEmployees.CanFocus = true;
			this.ycheckShowEmployees.Name = "ycheckShowEmployees";
			this.ycheckShowEmployees.Label = "";
			this.ycheckShowEmployees.DrawIndicator = true;
			this.ycheckShowEmployees.UseUnderline = true;
			this.table1.Add(this.ycheckShowEmployees);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.ycheckShowEmployees]));
			w9.TopAttach = ((uint)(8));
			w9.BottomAttach = ((uint)(9));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ycheckShowStock = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckShowStock.CanFocus = true;
			this.ycheckShowStock.Name = "ycheckShowStock";
			this.ycheckShowStock.Label = "";
			this.ycheckShowStock.DrawIndicator = true;
			this.ycheckShowStock.UseUnderline = true;
			this.table1.Add(this.ycheckShowStock);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.ycheckShowStock]));
			w10.TopAttach = ((uint)(7));
			w10.BottomAttach = ((uint)(8));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabel5 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel5.Name = "ylabel5";
			this.ylabel5.Xalign = 1F;
			this.ylabel5.LabelProp = global::Mono.Unix.Catalog.GetString("Вид отчета");
			this.table1.Add(this.ylabel5);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabel5]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelExcludeInVacation = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelExcludeInVacation.Name = "ylabelExcludeInVacation";
			this.ylabelExcludeInVacation.Xalign = 1F;
			this.ylabelExcludeInVacation.LabelProp = global::Mono.Unix.Catalog.GetString("Исключить сотрудников в отпуске");
			this.table1.Add(this.ylabelExcludeInVacation);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelExcludeInVacation]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelGroupByNormAmount = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelGroupByNormAmount.Name = "ylabelGroupByNormAmount";
			this.ylabelGroupByNormAmount.Xalign = 1F;
			this.ylabelGroupByNormAmount.LabelProp = global::Mono.Unix.Catalog.GetString("Группировать по количеству к выдаче");
			this.table1.Add(this.ylabelGroupByNormAmount);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelGroupByNormAmount]));
			w13.TopAttach = ((uint)(6));
			w13.BottomAttach = ((uint)(7));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelGroupBySubdivision = new global::Gtk.Label();
			this.ylabelGroupBySubdivision.Name = "ylabelGroupBySubdivision";
			this.ylabelGroupBySubdivision.Xalign = 1F;
			this.ylabelGroupBySubdivision.LabelProp = global::Mono.Unix.Catalog.GetString("Группировать по подразделениям");
			this.table1.Add(this.ylabelGroupBySubdivision);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelGroupBySubdivision]));
			w14.TopAttach = ((uint)(5));
			w14.BottomAttach = ((uint)(6));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelShowEmployees = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelShowEmployees.Name = "ylabelShowEmployees";
			this.ylabelShowEmployees.Xalign = 1F;
			this.ylabelShowEmployees.LabelProp = global::Mono.Unix.Catalog.GetString("Показывать списки сотрудников");
			this.table1.Add(this.ylabelShowEmployees);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelShowEmployees]));
			w15.TopAttach = ((uint)(8));
			w15.BottomAttach = ((uint)(9));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelShowSex = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelShowSex.Name = "ylabelShowSex";
			this.ylabelShowSex.Xalign = 1F;
			this.ylabelShowSex.LabelProp = global::Mono.Unix.Catalog.GetString("Детализировать по полу");
			this.table1.Add(this.ylabelShowSex);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelShowSex]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelShowSize = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelShowSize.Name = "ylabelShowSize";
			this.ylabelShowSize.Xalign = 1F;
			this.ylabelShowSize.LabelProp = global::Mono.Unix.Catalog.GetString("Детализировать по размерам");
			this.table1.Add(this.ylabelShowSize);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelShowSize]));
			w17.TopAttach = ((uint)(4));
			w17.BottomAttach = ((uint)(5));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelShowStock = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelShowStock.Name = "ylabelShowStock";
			this.ylabelShowStock.Xalign = 1F;
			this.ylabelShowStock.LabelProp = global::Mono.Unix.Catalog.GetString("Показывать количество на складе");
			this.table1.Add(this.ylabelShowStock);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelShowStock]));
			w18.TopAttach = ((uint)(7));
			w18.BottomAttach = ((uint)(8));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table1]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander(null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.expander1.Expanded = true;
			// Container child expander1.Gtk.Container+ContainerChild
			this.choiceprotectiontoolsview1 = new global::QS.Views.Control.ChoiceListView();
			this.choiceprotectiontoolsview1.Events = ((global::Gdk.EventMask)(256));
			this.choiceprotectiontoolsview1.Name = "choiceprotectiontoolsview1";
			this.expander1.Add(this.choiceprotectiontoolsview1);
			this.GtkLabel10 = new global::Gtk.Label();
			this.GtkLabel10.Name = "GtkLabel10";
			this.GtkLabel10.LabelProp = global::Mono.Unix.Catalog.GetString("Номенклатура нормы:");
			this.GtkLabel10.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel10;
			this.vbox1.Add(this.expander1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.expander1]));
			w21.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.expander2 = new global::Gtk.Expander(null);
			this.expander2.CanFocus = true;
			this.expander2.Name = "expander2";
			this.expander2.Expanded = true;
			// Container child expander2.Gtk.Container+ContainerChild
			this.choicesubdivisionview1 = new global::QS.Views.Control.ChoiceListView();
			this.choicesubdivisionview1.Events = ((global::Gdk.EventMask)(256));
			this.choicesubdivisionview1.Name = "choicesubdivisionview1";
			this.expander2.Add(this.choicesubdivisionview1);
			this.GtkLabel14 = new global::Gtk.Label();
			this.GtkLabel14.Name = "GtkLabel14";
			this.GtkLabel14.LabelProp = global::Mono.Unix.Catalog.GetString("Подразделение:");
			this.GtkLabel14.UseUnderline = true;
			this.expander2.LabelWidget = this.GtkLabel14;
			this.vbox1.Add(this.expander2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.expander2]));
			w23.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.expanderEmployeeGroups = new global::Gtk.Expander(null);
			this.expanderEmployeeGroups.CanFocus = true;
			this.expanderEmployeeGroups.Name = "expanderEmployeeGroups";
			// Container child expanderEmployeeGroups.Gtk.Container+ContainerChild
			this.choiceemployeegroupview1 = new global::QS.Views.Control.ChoiceListView();
			this.choiceemployeegroupview1.Events = ((global::Gdk.EventMask)(256));
			this.choiceemployeegroupview1.Name = "choiceemployeegroupview1";
			this.expanderEmployeeGroups.Add(this.choiceemployeegroupview1);
			this.GtkLabel18 = new global::Gtk.Label();
			this.GtkLabel18.Name = "GtkLabel18";
			this.GtkLabel18.LabelProp = global::Mono.Unix.Catalog.GetString("Группы сотрудников");
			this.GtkLabel18.UseUnderline = true;
			this.expanderEmployeeGroups.LabelWidget = this.GtkLabel18;
			this.vbox1.Add(this.expanderEmployeeGroups);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.expanderEmployeeGroups]));
			w25.Position = 3;
			w25.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ybuttonRun = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonRun.CanFocus = true;
			this.ybuttonRun.Name = "ybuttonRun";
			this.ybuttonRun.UseUnderline = true;
			this.ybuttonRun.Label = global::Mono.Unix.Catalog.GetString("Построить отчёт");
			this.vbox1.Add(this.ybuttonRun);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.ybuttonRun]));
			w26.Position = 4;
			w26.Expand = false;
			w26.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.expander1.Activated += new global::System.EventHandler(this.OnExpander1Activated);
			this.expander2.Activated += new global::System.EventHandler(this.OnExpander2Activated);
			this.expanderEmployeeGroups.Activated += new global::System.EventHandler(this.OnExpander3Activated);
			this.ybuttonRun.Clicked += new global::System.EventHandler(this.OnYbuttonRunClicked);
		}
	}
}
