
// This file has been generated by the GUI designer. Do not modify.
namespace Workwear.Views.ClothingService
{
	public partial class ClothingMoveView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::Gamma.Widgets.CleanableEntry entrySearchBarcode;

		private global::Gamma.GtkWidgets.yButton ybuttonPrintLabel;

		private global::Workwear.Views.ClothingService.BarcodeInfoView barcodeinfoview1;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView treeOperations;

		private global::Gtk.Label GtkLabel3;

		private global::Gamma.GtkWidgets.yTable ytable1;

		private global::Gamma.Widgets.yEnumComboBox comboState;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gamma.GtkWidgets.yTextView textComment;

		private global::Gamma.GtkWidgets.yLabel ylabel4;

		private global::Gamma.GtkWidgets.yLabel ylabel6;

		private global::Gamma.GtkWidgets.yTable ytableServices;

		private global::Gamma.GtkWidgets.yButton buttonAccept;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Workwear.Views.ClothingService.ClothingMoveView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Workwear.Views.ClothingService.ClothingMoveView";
			// Container child Workwear.Views.ClothingService.ClothingMoveView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.Xalign = 1F;
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Штрих код:");
			this.hbox1.Add(this.ylabel1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ylabel1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entrySearchBarcode = new global::Gamma.Widgets.CleanableEntry();
			this.entrySearchBarcode.Events = ((global::Gdk.EventMask)(256));
			this.entrySearchBarcode.Name = "entrySearchBarcode";
			this.hbox1.Add(this.entrySearchBarcode);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entrySearchBarcode]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ybuttonPrintLabel = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonPrintLabel.CanFocus = true;
			this.ybuttonPrintLabel.Name = "ybuttonPrintLabel";
			this.ybuttonPrintLabel.UseUnderline = true;
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-print", global::Gtk.IconSize.Menu);
			this.ybuttonPrintLabel.Image = w3;
			this.hbox1.Add(this.ybuttonPrintLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ybuttonPrintLabel]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.barcodeinfoview1 = new global::Workwear.Views.ClothingService.BarcodeInfoView();
			this.barcodeinfoview1.Events = ((global::Gdk.EventMask)(256));
			this.barcodeinfoview1.Name = "barcodeinfoview1";
			this.vbox1.Add(this.barcodeinfoview1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.barcodeinfoview1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeOperations = new global::Gamma.GtkWidgets.yTreeView();
			this.treeOperations.CanFocus = true;
			this.treeOperations.Name = "treeOperations";
			this.GtkScrolledWindow.Add(this.treeOperations);
			this.GtkAlignment3.Add(this.GtkScrolledWindow);
			this.frame2.Add(this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Выполненные операции</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel3;
			this.vbox1.Add(this.frame2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame2]));
			w10.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ytable1 = new global::Gamma.GtkWidgets.yTable();
			this.ytable1.Name = "ytable1";
			this.ytable1.NRows = ((uint)(3));
			this.ytable1.NColumns = ((uint)(2));
			this.ytable1.RowSpacing = ((uint)(6));
			this.ytable1.ColumnSpacing = ((uint)(6));
			// Container child ytable1.Gtk.Table+TableChild
			this.comboState = new global::Gamma.Widgets.yEnumComboBox();
			this.comboState.Name = "comboState";
			this.comboState.ShowSpecialStateAll = false;
			this.comboState.ShowSpecialStateNot = false;
			this.comboState.UseShortTitle = false;
			this.comboState.DefaultFirst = false;
			this.ytable1.Add(this.comboState);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.ytable1[this.comboState]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textComment = new global::Gamma.GtkWidgets.yTextView();
			this.textComment.CanFocus = true;
			this.textComment.Name = "textComment";
			this.GtkScrolledWindow1.Add(this.textComment);
			this.ytable1.Add(this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.ytable1[this.GtkScrolledWindow1]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.ylabel4 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel4.Name = "ylabel4";
			this.ylabel4.Xalign = 1F;
			this.ylabel4.LabelProp = global::Mono.Unix.Catalog.GetString("Новый статус:");
			this.ytable1.Add(this.ylabel4);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.ytable1[this.ylabel4]));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.ylabel6 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel6.Name = "ylabel6";
			this.ylabel6.Xalign = 0F;
			this.ylabel6.LabelProp = global::Mono.Unix.Catalog.GetString("Комментарий:");
			this.ytable1.Add(this.ylabel6);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.ytable1[this.ylabel6]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.ytableServices = new global::Gamma.GtkWidgets.yTable();
			this.ytableServices.Name = "ytableServices";
			this.ytableServices.NRows = ((uint)(3));
			this.ytableServices.NColumns = ((uint)(3));
			this.ytableServices.RowSpacing = ((uint)(6));
			this.ytableServices.ColumnSpacing = ((uint)(6));
			this.ytable1.Add(this.ytableServices);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.ytable1[this.ytableServices]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.ytable1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.ytable1]));
			w17.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.buttonAccept = new global::Gamma.GtkWidgets.yButton();
			this.buttonAccept.CanFocus = true;
			this.buttonAccept.Name = "buttonAccept";
			this.buttonAccept.UseUnderline = true;
			this.buttonAccept.Label = global::Mono.Unix.Catalog.GetString("Изменить статус");
			global::Gtk.Image w18 = new global::Gtk.Image();
			w18.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
			this.buttonAccept.Image = w18;
			this.vbox1.Add(this.buttonAccept);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.buttonAccept]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.ybuttonPrintLabel.Clicked += new global::System.EventHandler(this.OnYbuttonPrintLabelClicked);
			this.buttonAccept.Clicked += new global::System.EventHandler(this.OnButtonAcceptClicked);
		}
	}
}
