
// This file has been generated by the GUI designer. Do not modify.
namespace Workwear.ReportParameters.Views
{
	public partial class ClothingServiceReportView
	{
		private global::Gtk.VBox vbox1;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbuttonshowclosed;

		private global::Gamma.GtkWidgets.yButton buttonRun;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Workwear.ReportParameters.Views.ClothingServiceReportView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Workwear.ReportParameters.Views.ClothingServiceReportView";
			// Container child Workwear.ReportParameters.Views.ClothingServiceReportView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ycheckbuttonshowclosed = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbuttonshowclosed.CanFocus = true;
			this.ycheckbuttonshowclosed.Name = "ycheckbuttonshowclosed";
			this.ycheckbuttonshowclosed.Label = global::Mono.Unix.Catalog.GetString("Показывать закрытые");
			this.ycheckbuttonshowclosed.DrawIndicator = true;
			this.ycheckbuttonshowclosed.UseUnderline = true;
			this.vbox1.Add(this.ycheckbuttonshowclosed);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.ycheckbuttonshowclosed]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.buttonRun = new global::Gamma.GtkWidgets.yButton();
			this.buttonRun.CanFocus = true;
			this.buttonRun.Name = "buttonRun";
			this.buttonRun.UseUnderline = true;
			this.buttonRun.Label = global::Mono.Unix.Catalog.GetString("Сформировать отчет");
			this.vbox1.Add(this.buttonRun);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.buttonRun]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 2;
			w2.Expand = false;
			w2.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
