
// This file has been generated by the GUI designer. Do not modify.
namespace Workwear.ReportParameters.Views
{
	public partial class ShipmentReportView
	{
		private global::Gamma.GtkWidgets.yVBox yvbox1;

		private global::Gtk.Expander expander1;

		private global::QS.Views.Control.ChoiceListView choiceprotectiontoolsview1;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.Expander expander2;

		private global::QS.Views.Control.ChoiceListView choiceshipmentview;

		private global::Gtk.Label GtkLabel5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Workwear.ReportParameters.Views.ShipmentReportView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Workwear.ReportParameters.Views.ShipmentReportView";
			// Container child Workwear.ReportParameters.Views.ShipmentReportView.Gtk.Container+ContainerChild
			this.yvbox1 = new global::Gamma.GtkWidgets.yVBox();
			this.yvbox1.Name = "yvbox1";
			this.yvbox1.Spacing = 6;
			// Container child yvbox1.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander(null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.expander1.Expanded = true;
			// Container child expander1.Gtk.Container+ContainerChild
			this.choiceprotectiontoolsview1 = new global::QS.Views.Control.ChoiceListView();
			this.choiceprotectiontoolsview1.Events = ((global::Gdk.EventMask)(256));
			this.choiceprotectiontoolsview1.Name = "choiceprotectiontoolsview1";
			this.expander1.Add(this.choiceprotectiontoolsview1);
			this.GtkLabel4 = new global::Gtk.Label();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("Номенклатуры нормы");
			this.GtkLabel4.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel4;
			this.yvbox1.Add(this.expander1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.yvbox1[this.expander1]));
			w2.Position = 0;
			// Container child yvbox1.Gtk.Box+BoxChild
			this.expander2 = new global::Gtk.Expander(null);
			this.expander2.CanFocus = true;
			this.expander2.Name = "expander2";
			this.expander2.Expanded = true;
			// Container child expander2.Gtk.Container+ContainerChild
			this.choiceshipmentview = new global::QS.Views.Control.ChoiceListView();
			this.choiceshipmentview.Events = ((global::Gdk.EventMask)(256));
			this.choiceshipmentview.Name = "choiceshipmentview";
			this.expander2.Add(this.choiceshipmentview);
			this.GtkLabel5 = new global::Gtk.Label();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("Документы поставки");
			this.GtkLabel5.UseUnderline = true;
			this.expander2.LabelWidget = this.GtkLabel5;
			this.yvbox1.Add(this.expander2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.yvbox1[this.expander2]));
			w4.Position = 1;
			this.Add(this.yvbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
