
// This file has been generated by the GUI designer. Do not modify.
namespace Workwear.Views.Operations
{
	public partial class ManualEmployeeIssueOperationsView
	{
		private global::Gamma.GtkWidgets.yTable ytable1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewOperations;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button buttonSave;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.VSeparator vseparator1;

		private global::Gamma.GtkWidgets.yHBox yhbox2;

		private global::Gamma.GtkWidgets.yButton ybuttonAdd;

		private global::Gamma.GtkWidgets.yButton ybuttonDelete;

		private global::Gamma.GtkWidgets.yTable ytable2;

		private global::Gamma.Widgets.yListComboBox comboHeight;

		private global::Gamma.Widgets.yListComboBox comboSize;

		private global::QS.Views.Control.EntityEntry entityNomenclature;

		private global::Gamma.GtkWidgets.yHBox hboxBarcodeButtons;

		private global::Gamma.GtkWidgets.yButton buttonCreateOrDeleteBarcodes;

		private global::Gamma.GtkWidgets.yButton buttonPrintBarcodes;

		private global::Gamma.GtkWidgets.yLabel labelBarcodes;

		private global::Gamma.GtkWidgets.yLabel labelHeight;

		private global::Gamma.GtkWidgets.yLabel labelSize;

		private global::Gamma.GtkWidgets.yCheckButton ycheckOverrideBefore;

		private global::Gamma.Widgets.yDatePicker ydatepicker;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::Gamma.GtkWidgets.yLabel ylabel2;

		private global::Gamma.GtkWidgets.yLabel ylabel3;

		private global::Gamma.GtkWidgets.yLabel ylabelBarcodeTitle;

		private global::Gamma.GtkWidgets.ySpinButton yspinbuttonAmmount;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Workwear.Views.Operations.ManualEmployeeIssueOperationsView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Workwear.Views.Operations.ManualEmployeeIssueOperationsView";
			// Container child Workwear.Views.Operations.ManualEmployeeIssueOperationsView.Gtk.Container+ContainerChild
			this.ytable1 = new global::Gamma.GtkWidgets.yTable();
			this.ytable1.Name = "ytable1";
			this.ytable1.NRows = ((uint)(3));
			this.ytable1.NColumns = ((uint)(2));
			this.ytable1.RowSpacing = ((uint)(6));
			this.ytable1.ColumnSpacing = ((uint)(6));
			// Container child ytable1.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytreeviewOperations = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewOperations.CanFocus = true;
			this.ytreeviewOperations.Name = "ytreeviewOperations";
			this.GtkScrolledWindow.Add(this.ytreeviewOperations);
			this.ytable1.Add(this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.ytable1[this.GtkScrolledWindow]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			// Container child ytable1.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w3;
			this.hbox4.Add(this.buttonSave);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonSave]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Отменить");
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w5;
			this.hbox4.Add(this.buttonCancel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonCancel]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.Name = "vseparator1";
			this.hbox4.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vseparator1]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.ytable1.Add(this.hbox4);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.ytable1[this.hbox4]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.yhbox2 = new global::Gamma.GtkWidgets.yHBox();
			this.yhbox2.Name = "yhbox2";
			this.yhbox2.Spacing = 6;
			// Container child yhbox2.Gtk.Box+BoxChild
			this.ybuttonAdd = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonAdd.CanFocus = true;
			this.ybuttonAdd.Name = "ybuttonAdd";
			this.ybuttonAdd.UseUnderline = true;
			this.ybuttonAdd.Label = global::Mono.Unix.Catalog.GetString("Добавить");
			this.yhbox2.Add(this.ybuttonAdd);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.yhbox2[this.ybuttonAdd]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child yhbox2.Gtk.Box+BoxChild
			this.ybuttonDelete = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonDelete.CanFocus = true;
			this.ybuttonDelete.Name = "ybuttonDelete";
			this.ybuttonDelete.UseUnderline = true;
			this.ybuttonDelete.Label = global::Mono.Unix.Catalog.GetString("Удалить");
			this.yhbox2.Add(this.ybuttonDelete);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.yhbox2[this.ybuttonDelete]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.ytable1.Add(this.yhbox2);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.ytable1[this.yhbox2]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.ytable2 = new global::Gamma.GtkWidgets.yTable();
			this.ytable2.Name = "ytable2";
			this.ytable2.NRows = ((uint)(8));
			this.ytable2.NColumns = ((uint)(2));
			this.ytable2.RowSpacing = ((uint)(6));
			this.ytable2.ColumnSpacing = ((uint)(6));
			// Container child ytable2.Gtk.Table+TableChild
			this.comboHeight = new global::Gamma.Widgets.yListComboBox();
			this.comboHeight.Name = "comboHeight";
			this.comboHeight.AddIfNotExist = false;
			this.comboHeight.DefaultFirst = false;
			this.ytable2.Add(this.comboHeight);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.ytable2[this.comboHeight]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.comboSize = new global::Gamma.Widgets.yListComboBox();
			this.comboSize.Name = "comboSize";
			this.comboSize.AddIfNotExist = false;
			this.comboSize.DefaultFirst = false;
			this.ytable2.Add(this.comboSize);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.ytable2[this.comboSize]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.entityNomenclature = new global::QS.Views.Control.EntityEntry();
			this.entityNomenclature.Events = ((global::Gdk.EventMask)(256));
			this.entityNomenclature.Name = "entityNomenclature";
			this.ytable2.Add(this.entityNomenclature);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.ytable2[this.entityNomenclature]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.hboxBarcodeButtons = new global::Gamma.GtkWidgets.yHBox();
			this.hboxBarcodeButtons.Name = "hboxBarcodeButtons";
			this.hboxBarcodeButtons.Spacing = 6;
			// Container child hboxBarcodeButtons.Gtk.Box+BoxChild
			this.buttonCreateOrDeleteBarcodes = new global::Gamma.GtkWidgets.yButton();
			this.buttonCreateOrDeleteBarcodes.CanFocus = true;
			this.buttonCreateOrDeleteBarcodes.Name = "buttonCreateOrDeleteBarcodes";
			this.buttonCreateOrDeleteBarcodes.UseUnderline = true;
			this.buttonCreateOrDeleteBarcodes.Label = global::Mono.Unix.Catalog.GetString("Создать штрихкоды");
			global::Gtk.Image w15 = new global::Gtk.Image();
			w15.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Workwear.icon.buttons.barcode-add.png");
			this.buttonCreateOrDeleteBarcodes.Image = w15;
			this.hboxBarcodeButtons.Add(this.buttonCreateOrDeleteBarcodes);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hboxBarcodeButtons[this.buttonCreateOrDeleteBarcodes]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hboxBarcodeButtons.Gtk.Box+BoxChild
			this.buttonPrintBarcodes = new global::Gamma.GtkWidgets.yButton();
			this.buttonPrintBarcodes.CanFocus = true;
			this.buttonPrintBarcodes.Name = "buttonPrintBarcodes";
			this.buttonPrintBarcodes.UseUnderline = true;
			this.buttonPrintBarcodes.Label = global::Mono.Unix.Catalog.GetString("Печать штрихкодов");
			global::Gtk.Image w17 = new global::Gtk.Image();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-print", global::Gtk.IconSize.Menu);
			this.buttonPrintBarcodes.Image = w17;
			this.hboxBarcodeButtons.Add(this.buttonPrintBarcodes);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hboxBarcodeButtons[this.buttonPrintBarcodes]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.ytable2.Add(this.hboxBarcodeButtons);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.ytable2[this.hboxBarcodeButtons]));
			w19.TopAttach = ((uint)(7));
			w19.BottomAttach = ((uint)(8));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.labelBarcodes = new global::Gamma.GtkWidgets.yLabel();
			this.labelBarcodes.Name = "labelBarcodes";
			this.labelBarcodes.LabelProp = global::Mono.Unix.Catalog.GetString("ylabel5");
			this.ytable2.Add(this.labelBarcodes);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.ytable2[this.labelBarcodes]));
			w20.TopAttach = ((uint)(6));
			w20.BottomAttach = ((uint)(7));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.labelHeight = new global::Gamma.GtkWidgets.yLabel();
			this.labelHeight.Name = "labelHeight";
			this.labelHeight.Xalign = 1F;
			this.labelHeight.LabelProp = global::Mono.Unix.Catalog.GetString("Рост:");
			this.ytable2.Add(this.labelHeight);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.ytable2[this.labelHeight]));
			w21.TopAttach = ((uint)(3));
			w21.BottomAttach = ((uint)(4));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.labelSize = new global::Gamma.GtkWidgets.yLabel();
			this.labelSize.Name = "labelSize";
			this.labelSize.Xalign = 1F;
			this.labelSize.LabelProp = global::Mono.Unix.Catalog.GetString("Размер:");
			this.ytable2.Add(this.labelSize);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.ytable2[this.labelSize]));
			w22.TopAttach = ((uint)(2));
			w22.BottomAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.ycheckOverrideBefore = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckOverrideBefore.CanFocus = true;
			this.ycheckOverrideBefore.Name = "ycheckOverrideBefore";
			this.ycheckOverrideBefore.Label = global::Mono.Unix.Catalog.GetString("Сбрасывает предыдущие движения");
			this.ycheckOverrideBefore.DrawIndicator = true;
			this.ycheckOverrideBefore.UseUnderline = true;
			this.ytable2.Add(this.ycheckOverrideBefore);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.ytable2[this.ycheckOverrideBefore]));
			w23.TopAttach = ((uint)(5));
			w23.BottomAttach = ((uint)(6));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.ydatepicker = new global::Gamma.Widgets.yDatePicker();
			this.ydatepicker.Events = ((global::Gdk.EventMask)(256));
			this.ydatepicker.Name = "ydatepicker";
			this.ydatepicker.WithTime = false;
			this.ydatepicker.Date = new global::System.DateTime(0);
			this.ydatepicker.IsEditable = true;
			this.ydatepicker.AutoSeparation = true;
			this.ytable2.Add(this.ydatepicker);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.ytable2[this.ydatepicker]));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.Xalign = 1F;
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString(" Дата:");
			this.ytable2.Add(this.ylabel1);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.ytable2[this.ylabel1]));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.ylabel2 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel2.Name = "ylabel2";
			this.ylabel2.Xalign = 1F;
			this.ylabel2.LabelProp = global::Mono.Unix.Catalog.GetString("Количество:");
			this.ytable2.Add(this.ylabel2);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.ytable2[this.ylabel2]));
			w26.TopAttach = ((uint)(4));
			w26.BottomAttach = ((uint)(5));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.ylabel3 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel3.Name = "ylabel3";
			this.ylabel3.Xalign = 1F;
			this.ylabel3.LabelProp = global::Mono.Unix.Catalog.GetString("Номенклатура:");
			this.ytable2.Add(this.ylabel3);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.ytable2[this.ylabel3]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.ylabelBarcodeTitle = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelBarcodeTitle.Name = "ylabelBarcodeTitle";
			this.ylabelBarcodeTitle.Xalign = 1F;
			this.ylabelBarcodeTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Штрих коды:");
			this.ytable2.Add(this.ylabelBarcodeTitle);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.ytable2[this.ylabelBarcodeTitle]));
			w28.TopAttach = ((uint)(6));
			w28.BottomAttach = ((uint)(7));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable2.Gtk.Table+TableChild
			this.yspinbuttonAmmount = new global::Gamma.GtkWidgets.ySpinButton(0D, 100D, 1D);
			this.yspinbuttonAmmount.CanFocus = true;
			this.yspinbuttonAmmount.Name = "yspinbuttonAmmount";
			this.yspinbuttonAmmount.Adjustment.PageIncrement = 10D;
			this.yspinbuttonAmmount.ClimbRate = 1D;
			this.yspinbuttonAmmount.Numeric = true;
			this.yspinbuttonAmmount.ValueAsDecimal = 0m;
			this.yspinbuttonAmmount.ValueAsInt = 0;
			this.ytable2.Add(this.yspinbuttonAmmount);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.ytable2[this.yspinbuttonAmmount]));
			w29.TopAttach = ((uint)(4));
			w29.BottomAttach = ((uint)(5));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			this.ytable1.Add(this.ytable2);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.ytable1[this.ytable2]));
			w30.TopAttach = ((uint)(1));
			w30.BottomAttach = ((uint)(2));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.ytable1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
