
// This file has been generated by the GUI designer. Do not modify.
namespace Workwear.Views.Regulations.NormChildren
{
	public partial class NormPostsView
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytreeProfessions;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Button buttonNewProfession;

		private global::Gtk.Button buttonAddProfession;

		private global::Gtk.Button buttonRemoveProfession;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Workwear.Views.Regulations.NormChildren.NormPostsView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Workwear.Views.Regulations.NormChildren.NormPostsView";
			// Container child Workwear.Views.Regulations.NormChildren.NormPostsView.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytreeProfessions = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeProfessions.CanFocus = true;
			this.ytreeProfessions.Name = "ytreeProfessions";
			this.GtkScrolledWindow.Add(this.ytreeProfessions);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.buttonNewProfession = new global::Gtk.Button();
			this.buttonNewProfession.CanFocus = true;
			this.buttonNewProfession.Name = "buttonNewProfession";
			this.buttonNewProfession.UseUnderline = true;
			this.buttonNewProfession.Label = global::Mono.Unix.Catalog.GetString("Новая");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-new", global::Gtk.IconSize.Menu);
			this.buttonNewProfession.Image = w3;
			this.hbox5.Add(this.buttonNewProfession);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.buttonNewProfession]));
			w4.Position = 0;
			w4.Expand = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.buttonAddProfession = new global::Gtk.Button();
			this.buttonAddProfession.CanFocus = true;
			this.buttonAddProfession.Name = "buttonAddProfession";
			this.buttonAddProfession.UseUnderline = true;
			this.buttonAddProfession.Label = global::Mono.Unix.Catalog.GetString("Добавить");
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonAddProfession.Image = w5;
			this.hbox5.Add(this.buttonAddProfession);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.buttonAddProfession]));
			w6.Position = 1;
			w6.Expand = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.buttonRemoveProfession = new global::Gtk.Button();
			this.buttonRemoveProfession.Sensitive = false;
			this.buttonRemoveProfession.CanFocus = true;
			this.buttonRemoveProfession.Name = "buttonRemoveProfession";
			this.buttonRemoveProfession.UseUnderline = true;
			this.buttonRemoveProfession.Label = global::Mono.Unix.Catalog.GetString("Убрать");
			global::Gtk.Image w7 = new global::Gtk.Image();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.buttonRemoveProfession.Image = w7;
			this.hbox5.Add(this.buttonRemoveProfession);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.buttonRemoveProfession]));
			w8.Position = 2;
			w8.Expand = false;
			this.vbox2.Add(this.hbox5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.buttonNewProfession.Clicked += new global::System.EventHandler(this.OnButtonNewProfessionClicked);
			this.buttonAddProfession.Clicked += new global::System.EventHandler(this.OnButtonAddProfessionClicked);
			this.buttonRemoveProfession.Clicked += new global::System.EventHandler(this.OnButtonRemoveProfessionClicked);
		}
	}
}
