
// This file has been generated by the GUI designer. Do not modify.
namespace workwear.Journal.Filter.Views.Stock
{
	public partial class StockBalanceFilterView
	{
		private global::Gtk.Table table1;

		private global::Gamma.GtkWidgets.yCheckButton chShowNegative;

		private global::Gtk.HBox hbox2;

		private global::QS.Views.Control.EntityEntry entityWarehouse;

		private global::Gamma.GtkWidgets.yLabel ylabelOwner;

		private global::Gamma.Widgets.ySpecComboBox yspeccomboboxOwners;

		private global::Gtk.HBox hbox4;

		private global::Gamma.Widgets.yEnumComboBox yenumcomboboxAmount;

		private global::Gamma.GtkWidgets.yHBox yhboxDuty;

		private global::Gtk.Label labelDuty;

		private global::QS.Views.Control.EntityEntry entityDutyNorm;

		private global::Gamma.GtkWidgets.yLabel labelAmount;

		private global::Gamma.GtkWidgets.yLabel labelWarehouse;

		private global::Gamma.GtkWidgets.yHBox yhbox1;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::Gamma.Widgets.yDatePicker ydateDate;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget workwear.Journal.Filter.Views.Stock.StockBalanceFilterView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "workwear.Journal.Filter.Views.Stock.StockBalanceFilterView";
			// Container child workwear.Journal.Filter.Views.Stock.StockBalanceFilterView.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.chShowNegative = new global::Gamma.GtkWidgets.yCheckButton();
			this.chShowNegative.CanFocus = true;
			this.chShowNegative.Name = "chShowNegative";
			this.chShowNegative.Label = global::Mono.Unix.Catalog.GetString("Показать отрицательный баланс");
			this.chShowNegative.DrawIndicator = true;
			this.chShowNegative.UseUnderline = true;
			this.chShowNegative.Xalign = 1F;
			this.table1.Add(this.chShowNegative);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.chShowNegative]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(2));
			w1.RightAttach = ((uint)(3));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entityWarehouse = new global::QS.Views.Control.EntityEntry();
			this.entityWarehouse.Events = ((global::Gdk.EventMask)(256));
			this.entityWarehouse.Name = "entityWarehouse";
			this.hbox2.Add(this.entityWarehouse);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entityWarehouse]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ylabelOwner = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelOwner.Name = "ylabelOwner";
			this.ylabelOwner.Xalign = 1F;
			this.ylabelOwner.LabelProp = global::Mono.Unix.Catalog.GetString("Собственник:");
			this.hbox2.Add(this.ylabelOwner);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.ylabelOwner]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.yspeccomboboxOwners = new global::Gamma.Widgets.ySpecComboBox();
			this.yspeccomboboxOwners.Name = "yspeccomboboxOwners";
			this.yspeccomboboxOwners.AddIfNotExist = false;
			this.yspeccomboboxOwners.DefaultFirst = false;
			this.yspeccomboboxOwners.ShowSpecialStateAll = true;
			this.yspeccomboboxOwners.ShowSpecialStateNot = true;
			this.yspeccomboboxOwners.NameForSpecialStateNot = "Без собственника";
			this.hbox2.Add(this.yspeccomboboxOwners);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.yspeccomboboxOwners]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.table1.Add(this.hbox2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox2]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.yenumcomboboxAmount = new global::Gamma.Widgets.yEnumComboBox();
			this.yenumcomboboxAmount.Name = "yenumcomboboxAmount";
			this.yenumcomboboxAmount.ShowSpecialStateAll = false;
			this.yenumcomboboxAmount.ShowSpecialStateNot = false;
			this.yenumcomboboxAmount.UseShortTitle = false;
			this.yenumcomboboxAmount.DefaultFirst = false;
			this.hbox4.Add(this.yenumcomboboxAmount);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.yenumcomboboxAmount]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.yhboxDuty = new global::Gamma.GtkWidgets.yHBox();
			this.yhboxDuty.Name = "yhboxDuty";
			this.yhboxDuty.Spacing = 6;
			// Container child yhboxDuty.Gtk.Box+BoxChild
			this.labelDuty = new global::Gtk.Label();
			this.labelDuty.Name = "labelDuty";
			this.labelDuty.Xalign = 1F;
			this.labelDuty.LabelProp = global::Mono.Unix.Catalog.GetString("Дежурная норма:");
			this.yhboxDuty.Add(this.labelDuty);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.yhboxDuty[this.labelDuty]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child yhboxDuty.Gtk.Box+BoxChild
			this.entityDutyNorm = new global::QS.Views.Control.EntityEntry();
			this.entityDutyNorm.Events = ((global::Gdk.EventMask)(256));
			this.entityDutyNorm.Name = "entityDutyNorm";
			this.yhboxDuty.Add(this.entityDutyNorm);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.yhboxDuty[this.entityDutyNorm]));
			w8.Position = 1;
			this.hbox4.Add(this.yhboxDuty);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.yhboxDuty]));
			w9.Position = 1;
			this.table1.Add(this.hbox4);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox4]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelAmount = new global::Gamma.GtkWidgets.yLabel();
			this.labelAmount.Name = "labelAmount";
			this.labelAmount.Xalign = 1F;
			this.labelAmount.LabelProp = global::Mono.Unix.Catalog.GetString("В количестве:");
			this.table1.Add(this.labelAmount);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.labelAmount]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelWarehouse = new global::Gamma.GtkWidgets.yLabel();
			this.labelWarehouse.Name = "labelWarehouse";
			this.labelWarehouse.Xalign = 1F;
			this.labelWarehouse.LabelProp = global::Mono.Unix.Catalog.GetString("Склад:");
			this.table1.Add(this.labelWarehouse);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.labelWarehouse]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.yhbox1 = new global::Gamma.GtkWidgets.yHBox();
			this.yhbox1.Name = "yhbox1";
			this.yhbox1.Spacing = 6;
			// Container child yhbox1.Gtk.Box+BoxChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.Xalign = 1F;
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Дата:");
			this.yhbox1.Add(this.ylabel1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.yhbox1[this.ylabel1]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child yhbox1.Gtk.Box+BoxChild
			this.ydateDate = new global::Gamma.Widgets.yDatePicker();
			this.ydateDate.Events = ((global::Gdk.EventMask)(256));
			this.ydateDate.Name = "ydateDate";
			this.ydateDate.WithTime = false;
			this.ydateDate.Date = new global::System.DateTime(0);
			this.ydateDate.IsEditable = true;
			this.ydateDate.AutoSeparation = true;
			this.yhbox1.Add(this.ydateDate);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.yhbox1[this.ydateDate]));
			w14.Position = 1;
			this.table1.Add(this.yhbox1);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.yhbox1]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
